"""``bay compile``: fleet file + pinned bay.toml files -> ``group_vars/all/services.yml``.

A pure function of its inputs (see :mod:`bay_cli.fleet`): the same inputs give
byte-identical output. The output carries a hash header; a hand edit makes the
next compile refuse (the command checks that, see ``commands/compile_cmd.py``).

Mapping, one bay.toml environment at a time:

* Container names: ``<name>`` for the primary env, ``<name>-<env>`` otherwise;
  extra services ``<name>-<service>`` / ``<name>-<env>-<service>``. The
  services.yml key IS the container name. Lockfile ``adopted.containers``
  (keyed by service, the main container is ``web``) wins.
* A routed container (``public``/``tailnet``, or a service with ``domain``)
  becomes a ``services:`` entry. An unrouted one (``internal``, or a service
  with neither ``domain`` nor ``path``) becomes an ``accessories:`` entry:
  today that is the only way to run a container with no router.
* ``health`` maps to ``healthcheck_path`` (the probe and the password
  carve-out), never to the Docker ``healthcheck`` block.
* Secret names resolve to the secret ``<MAIN CONTAINER>_<NAME>``, so every
  container of one project environment reads the same value.
* Features the deploy code cannot express yet are reported as
  :class:`Unsupported` (``# TODO(role)``) and the command refuses unless
  ``--allow-unsupported``; with it, the closest expressible form is emitted.

Collisions (container, router, volume, domain, database, database user and
variable names) are errors that name both sides. Nothing is last-wins.

Fleet-wide: ``[webhook]`` becomes ``webhook:`` and ``[tailnet.routes.*]``
becomes ``tailnet_proxies:`` (see :mod:`bay_cli.routes`). The compile refuses
when a hand file in ``group_vars/all`` still defines ``tailnet_proxies`` and
the fleet file has routes: both would set the same variable.
"""

from __future__ import annotations

import copy
import hashlib
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from bay_cli import routes
from bay_cli.bay_toml import sibling_var
from bay_cli.fleet import FILES_DIR, FLEET_PREFIX, PROJECTS_DIR, FleetInputs, LockEnv, Project

HEADER_TEXT = (
    "# GENERATED by bay compile. sha256:{digest}. Do not edit; edit bay.toml or bay.fleet.toml."
)
HEADER_RE = re.compile(
    r"^# GENERATED by bay compile\. sha256:([0-9a-f]{64})\. "
    r"Do not edit; edit bay\.toml or bay\.fleet\.toml\.$"
)

#: Keys a [deploy.<env>] table may override with a plain replace.
_RUNTIME_KEYS = (
    "image", "port", "command", "release", "health", "replicas", "memory", "update",
    "zero_downtime", "logs", "secrets", "log_rotation",
)
#: bay.toml update -> services.yml update. None means: leave the key out (monitor).
_UPDATE = {"notify": None, "auto": "auto", "off": False}
#: Variables env.j2 writes for a `database:` binding.
_DB_VARS = ("DATABASE_URL", "DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASSWORD")
_PG_PORT = 5432
_REDIS_PORT = 6379
#: Names the deploy code derives from a container name: routers and the canary.
_DERIVED_SUFFIXES = ("-vpn", "-public", "-health", "-new")
#: services.schema.json: what a route may contain.
_ROUTE_RE = re.compile(r"^/[A-Za-z0-9._~%+/*-]*$")


class CompileError(Exception):
    """The inputs cannot be compiled. ``lines`` holds one message each."""

    def __init__(self, lines: list[str]) -> None:
        super().__init__("\n".join(lines))
        self.lines = lines


@dataclass(frozen=True, order=True)
class Unsupported:
    """A bay.toml feature the deploy code cannot express yet."""

    project: str
    path: str
    feature: str

    def __str__(self) -> str:
        return f"# TODO(role) {self.project}: {self.path}: {self.feature}"


@dataclass
class CompileResult:
    services: dict[str, dict[str, Any]]
    accessories: dict[str, dict[str, Any]]
    webhook: dict[str, str] | None
    unsupported: list[Unsupported] = field(default_factory=list)
    #: Lines for the reader (a mounted file found in its old place). Never in the file.
    notes: list[str] = field(default_factory=list)
    #: ``[tailnet.routes]`` as the map the traefik and headscale templates read.
    tailnet_proxies: dict[str, dict[str, Any]] = field(default_factory=dict)

    def data(self) -> dict[str, Any]:
        out: dict[str, Any] = {"accessories": self.accessories, "services": self.services}
        if self.webhook is not None:
            out["webhook"] = self.webhook
        if self.tailnet_proxies:
            # Only when routes exist, so a fleet without them compiles to the same bytes.
            out["tailnet_proxies"] = self.tailnet_proxies
        return out

    def body(self) -> str:
        """The file without its header line. Deterministic."""
        import yaml

        data = self.data()
        proxies = data.pop("tailnet_proxies", None)
        dumped: str = yaml.safe_dump(
            data,
            sort_keys=True,
            default_flow_style=False,
            allow_unicode=True,
            width=4096,
            explicit_start=True,
        )
        if proxies:
            # Routes keep the order of bay.fleet.toml: the traefik and headscale
            # templates render them in that order, so an imported fleet renders
            # the same bytes as its old tailnet_proxies.yml did.
            dumped += yaml.safe_dump(
                {"tailnet_proxies": proxies},
                sort_keys=False,
                default_flow_style=False,
                allow_unicode=True,
                width=4096,
            )
        if not self.unsupported:
            return dumped
        head, rest = dumped.split("\n", 1)
        todo = "".join(f"{u}\n" for u in self.unsupported)
        return f"{head}\n{todo}{rest}"

    def text(self) -> str:
        body = self.body()
        return header_for(body) + "\n" + body


def header_for(body: str) -> str:
    return HEADER_TEXT.format(digest=hashlib.sha256(body.encode("utf-8")).hexdigest())


def split_header(text: str) -> tuple[str | None, str]:
    """Return (recorded digest or None, body) for a file on disk."""
    first, sep, rest = text.partition("\n")
    match = HEADER_RE.match(first)
    if not match:
        return None, text
    return match.group(1), rest if sep else ""


def body_digest(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


# ── Compiler ────────────────────────────────────────────────────────────────


@dataclass
class _Unit:
    """One project in one environment."""

    project: Project
    env: str
    primary: bool
    box: str
    lock: LockEnv
    eff: dict[str, Any]
    access: dict[str, Any]
    build: dict[str, Any] | None
    containers: dict[str, str]
    ports: dict[str, int]

    @property
    def doc(self) -> dict[str, Any]:
        return self.project.doc

    @property
    def deploy(self) -> dict[str, Any]:
        d: dict[str, Any] = self.doc["deploy"][self.env]
        return d

    @property
    def label(self) -> str:
        return f"{self.project.name} ({self.env})"

    @property
    def secret_prefix(self) -> str:
        return self.containers["web"].upper().replace("-", "_")


def compile_fleet(inputs: FleetInputs) -> CompileResult:
    """Compile the fleet. Raise CompileError listing every problem found."""
    return _Compiler(inputs).run()


class _Compiler:
    def __init__(self, inputs: FleetInputs) -> None:
        self.inputs = inputs
        self.fleet = inputs.fleet
        self.defaults: dict[str, Any] = self.fleet.get("defaults", {})
        self.boxes: dict[str, dict[str, Any]] = self.fleet["boxes"]
        self.resources: dict[str, dict[str, Any]] = self.fleet.get("resources", {})
        self.primary_env: str = self.fleet.get("primary_env", "production")
        self.errors: list[str] = []
        self.unsupported: set[Unsupported] = set()
        self.services: dict[str, dict[str, Any]] = {}
        self.accessories: dict[str, dict[str, Any]] = {}
        self.owners: dict[str, str] = {}
        self.domains: dict[str, str] = {}
        self.volumes: dict[str, str] = {}
        self.databases: dict[tuple[str, str], str] = {}
        self.db_users: dict[tuple[str, str], str] = {}
        self.units: dict[tuple[str, str], _Unit] = {}
        self.tailnet_exposed: set[str] = set()
        self.notes: set[str] = set()

    # ── driver ──────────────────────────────────────────────────────────
    def run(self) -> CompileResult:
        for key in sorted(self.resources):
            self._claim_container(key, f"resource {key} in bay.fleet.toml")
        for name in sorted(self.inputs.projects):
            project = self.inputs.projects[name]
            for env in sorted(project.doc["deploy"]):
                unit = self._unit(project, env)
                if unit is not None:
                    self.units[(name, env)] = unit
        self._check_derived_names()
        for key in sorted(self.resources):
            self._emit_resource(key, self.resources[key])
        for unit in self.units.values():
            self._emit_unit(unit)
        for name in sorted(self.tailnet_exposed):
            if name in self.services:
                self.services[name]["ports"]["expose"] = "tailnet"
        proxies = self._tailnet_proxies()
        webhook = self._webhook()
        if self.errors:
            raise CompileError(sorted(set(self.errors)))
        return CompileResult(
            services=self.services,
            accessories=self.accessories,
            webhook=webhook,
            unsupported=sorted(self.unsupported),
            notes=sorted(self.notes),
            tailnet_proxies=proxies,
        )

    def _err(self, msg: str) -> None:
        self.errors.append(msg)

    def _todo(self, unit: _Unit, path: str, feature: str) -> None:
        self.unsupported.add(Unsupported(unit.project.name, path, feature))

    # ── names ───────────────────────────────────────────────────────────
    def _claim_container(self, name: str, owner: str) -> None:
        if name in self.owners:
            self._err(f"container name {name} is used by both {self.owners[name]} and {owner}")
            return
        hand = self.inputs.hand_keys.get(name)
        if hand is not None:
            self._err(
                f"container name {name} from {owner} is also defined by hand in {hand}; "
                "remove one of them"
            )
        self.owners[name] = owner

    def _check_derived_names(self) -> None:
        for name in sorted(self.owners):
            for suffix in _DERIVED_SUFFIXES:
                base = name[: -len(suffix)]
                if name.endswith(suffix) and base in self.owners:
                    self._err(
                        f"container name {name} ({self.owners[name]}) collides with the "
                        f"{suffix} name Bay derives from {base} ({self.owners[base]})"
                    )

    def _container_name(self, project: Project, env: str, service: str, lock: LockEnv) -> str:
        if service in lock.containers:
            return lock.containers[service]
        base = project.name if env == self.primary_env else f"{project.name}-{env}"
        return base if service == "web" else f"{base}-{service}"

    def _volume_name(self, unit: _Unit, volume: str) -> str:
        if volume in unit.lock.volumes:
            return unit.lock.volumes[volume]
        name = unit.project.name
        return f"{name}-{volume}" if unit.primary else f"{name}-{unit.env}-{volume}"

    def _db_names(self, unit: _Unit) -> tuple[str, str]:
        base = unit.project.name.replace("-", "_")
        derived = base if unit.primary else f"{base}_{unit.env}"
        return unit.lock.database or derived, unit.lock.role or derived

    # ── units ───────────────────────────────────────────────────────────
    def _unit(self, project: Project, env: str) -> _Unit | None:
        doc = project.doc
        deploy = doc["deploy"][env]
        lock = project.lock_env(env)
        box = lock.box or deploy.get("box") or self.fleet["default_box"]
        where = f"{project.name}: deploy.{env}"
        if box not in self.boxes:
            self._err(f"{where}: box {box} is not in bay.fleet.toml [boxes]")
            return None

        eff: dict[str, Any] = {k: copy.deepcopy(doc[k]) for k in _RUNTIME_KEYS if k in doc}
        for k in _RUNTIME_KEYS:
            if k in deploy:
                eff[k] = copy.deepcopy(deploy[k])
        eff["env"] = {**doc.get("env", {}), **deploy.get("env", {})}

        access = copy.deepcopy(doc["access"])
        for k, v in deploy.get("access", {}).items():
            if isinstance(v, dict) and isinstance(access.get(k), dict):
                access[k] = {**access[k], **v}
            else:
                access[k] = copy.deepcopy(v)

        build: dict[str, Any] | None = None
        if "image" not in eff:
            build = copy.deepcopy(doc.get("build", {}))
            args = {**build.get("args", {}), **deploy.get("build", {}).get("args", {})}
            if args:
                build["args"] = args

        containers: dict[str, str] = {}
        ports: dict[str, int] = {}
        for service in ["web", *sorted(doc.get("services", {}))]:
            name = self._container_name(project, env, service, lock)
            containers[service] = name
            self._claim_container(name, f"{project.name} ({env}) {_svc_label(service)}")
            port = eff.get("port") if service == "web" else doc["services"][service].get("port")
            if isinstance(port, int):
                ports[service] = port
        return _Unit(
            project=project, env=env, primary=env == self.primary_env, box=box, lock=lock,
            eff=eff, access=access, build=build, containers=containers, ports=ports,
        )

    def _regions(self, boxes: list[str], who: str) -> list[str] | None:
        groups: list[str] = []
        for box in boxes:
            group = self.boxes[box].get("group")
            if group is None:
                env = self.boxes[box]["env"]
                peers = sorted(b for b, d in self.boxes.items() if d["env"] == env)
                if len(peers) > 1:
                    self._err(
                        f"{who}: box {box} has no group, but boxes {', '.join(peers)} all "
                        f"belong to env {env}; set group for each of them"
                    )
                return None
            if group not in groups:
                groups.append(group)
        return groups

    # ── resources ───────────────────────────────────────────────────────
    def _resource_boxes(self, res: dict[str, Any]) -> list[str]:
        placed = res.get("box", self.fleet["default_box"])
        return list(placed) if isinstance(placed, list) else [placed]

    def _emit_resource(self, key: str, res: dict[str, Any]) -> None:
        entry: dict[str, Any] = {"image": res["image"]}
        if "expose" in res:
            pair = f"{res['port']}:{res['port']}"
            if res["expose"] == "loopback":
                # Spell the bind out. The deploy role strips any address from
                # the string and binds 127.0.0.1 for loopback, so the container
                # spec is the same as for a bare pair. Never 0.0.0.0.
                entry["port"] = f"127.0.0.1:{pair}"
            else:
                entry["port"] = pair
                entry["expose"] = res["expose"]
        if "command" in res:
            entry["command"] = res["command"]
        if "memory" in res:
            # Swap is never allowed: memswap_limit equals the memory limit.
            entry["mem_limit"] = res["memory"]
            entry["memswap_limit"] = res["memory"]
        update = _UPDATE[res.get("update", "notify")]
        if update is not None:
            entry["update"] = update
        if "network_mode" in res:
            entry["network_mode"] = res["network_mode"]
        if res.get("volumes"):
            entry["volumes"] = list(res["volumes"])
            for spec in res["volumes"]:
                self._claim_resource_volume(key, spec)
        env: dict[str, Any] = {}
        if res.get("env"):
            env["clear"] = dict(res["env"])
        if res.get("secrets"):
            env["secret"] = dict(res["secrets"])
        if env:
            entry["env"] = env
        if "health" in res:
            entry["healthcheck"] = dict(res["health"])
        if "backup" in res:
            entry["backup"] = dict(res["backup"])
        if res.get("files"):
            entry["config_files"] = list(res["files"])
        if "files_mode" in res:
            entry["config_files_mode"] = res["files_mode"]
        regions = self._regions(self._resource_boxes(res), f"resource {key}")
        if regions:
            entry["regions"] = regions
        self.accessories[key] = entry

    def _claim_resource_volume(self, key: str, spec: str) -> None:
        # Bind mounts start with / or a template; only named volumes can collide.
        name = spec.split(":", 1)[0]
        if not name or name.startswith(("/", ".", "{")):
            return
        if spec.endswith(":ro"):
            return  # a read-only reader of a volume that a project owns is deliberate
        owner = f"resource {key}"
        if name in self.volumes and self.volumes[name] != owner:
            self._err(f"volume {name} is used by both {self.volumes[name]} and {owner}")
        self.volumes.setdefault(name, owner)

    def _find_resource(self, unit: _Unit, kind: str, path: str) -> str | None:
        on_box = [
            k for k, r in sorted(self.resources.items())
            if r.get("kind", "container") == kind and unit.box in self._resource_boxes(r)
        ]
        if len(on_box) == 1:
            return on_box[0]
        if len(on_box) > 1:
            self._err(
                f"{unit.label}: {path}: box {unit.box} has more than one {kind} resource "
                f"({', '.join(on_box)}); keep one per box"
            )
            return None
        elsewhere = [k for k, r in self.resources.items() if r.get("kind", "container") == kind]
        if elsewhere:
            self._todo(
                unit, path,
                f"{kind} on another box than {unit.box} (cross-box data access)",
            )
        else:
            self._err(f"{unit.label}: {path}: bay.fleet.toml defines no {kind} resource")
        return None

    # ── projects ────────────────────────────────────────────────────────
    def _emit_unit(self, unit: _Unit) -> None:
        doc = unit.doc
        for i, _job in enumerate(doc.get("jobs", [])):
            self._todo(unit, f"jobs[{i}]", "scheduled jobs")
        if "backup" in doc:
            self._todo(unit, "backup", "project backup schedule for volumes")
        for service in ["web", *sorted(doc.get("services", {}))]:
            self._emit_container(unit, service)

    def _emit_container(self, unit: _Unit, service: str) -> None:
        doc = unit.doc
        is_web = service == "web"
        level: dict[str, Any] = unit.eff if is_web else doc["services"][service]
        base = "" if is_web else f"services.{service}"
        name = unit.containers[service]
        inherit = is_web or level.get("inherit", True) is not False

        if is_web:
            access = unit.access
            mode = access["mode"]
            routed = mode in ("public", "tailnet")
        else:
            own = level.get("access", {})
            if "path" in level:
                self._todo(unit, _p(base, "path"), "routing a service by path on the main domain")
                return
            routed = "domain" in level
            access = own
            mode = own.get("mode", unit.access["mode"]) if routed else "internal"
            if routed and mode == "internal":
                self._err(
                    f"{unit.label}: {_p(base, 'domain')}: the service has a domain but takes "
                    "access.mode internal from the project; set its own access.mode"
                )
                return

        image, build = self._image(unit, service, level, inherit, base)
        env, database, depends = self._env(unit, service, level, inherit, base)
        # Mounts are never overridden per environment, so the main container
        # reads them from the top level of the file.
        volumes, files, files_public = self._mounts(unit, doc if is_web else level, base)

        entry: dict[str, Any] = {}
        if image is not None:
            entry["image"] = image
        if build is not None:
            entry["build"] = build
        if env:
            entry["env"] = env
        if depends:
            entry["depends_on"] = sorted(depends)
        if volumes:
            entry["volumes"] = volumes
        if files:
            entry["config_files"] = files
            if files_public:
                entry["config_files_mode"] = "public"
        if "memory" in level:
            # Swap is never allowed: memswap_limit equals the memory limit. A
            # container that runs today with only mem_limit gains the swap cap,
            # so its first deploy from a compiled file recreates it once.
            entry["mem_limit"] = level["memory"]
            entry["memswap_limit"] = level["memory"]
        rotation = level.get("log_rotation")
        if rotation:
            entry["log_rotation"] = dict(rotation)
        update_value = level.get("update", unit.eff.get("update", "notify"))
        update = _UPDATE[update_value]
        if update is not None:
            entry["update"] = update
        if "command" in level:
            entry["command"] = level["command"]
        if is_web and "release" in unit.eff:
            # [deploy.<env>] release replaces the top-level one (_RUNTIME_KEYS).
            entry["release"] = unit.eff["release"]
        logs = level.get("logs", unit.eff.get("logs", self.defaults.get("logs", "off")))
        retention = _log_retention(logs)
        if retention is not None:
            entry["log_retention"] = retention
        regions = self._regions([unit.box], unit.label)
        if regions:
            entry["regions"] = regions

        port = unit.ports.get(service)
        health = level.get("health")
        # The main container reads expose from the top level of the file;
        # it is never overridden per environment.
        expose = doc.get("expose") if is_web else level.get("expose")
        if not routed:
            if build is not None:
                self._todo(
                    unit, base or "access.mode", "an internal container that builds from source"
                )
                return
            if database is not None:
                self._todo(unit, _p(base, "needs.postgres"), "a database for an internal container")
            if isinstance(health, str) and health.startswith("/") and health != "/":
                self._todo(unit, _p(base, "health"), "a health path on an internal container")
            if level.get("zero_downtime") or level.get("replicas", 1) != 1:
                self._todo(
                    unit, base or "access.mode",
                    "zero_downtime or replicas on an internal container",
                )
            # The deploy code binds the box port equal to the container port.
            if expose is not None and port is not None:
                entry["port"] = f"{port}:{port}"
                if expose != "loopback":
                    entry["expose"] = expose
            self.accessories[name] = entry
            return

        assert port is not None  # the validator requires a port for routed containers
        entry["access"] = "public" if mode == "public" else "vpn"
        entry["ports"] = {"internal": port}
        if expose is not None:
            entry["ports"]["expose"] = expose
        if database is not None:
            entry["database"] = database
        if level.get("zero_downtime"):
            entry["zero_downtime"] = True
        replicas = level.get("replicas", 1)
        if replicas != 1:
            entry["replicas"] = replicas
        if isinstance(health, str) and health.startswith("/") and health != "/":
            entry["healthcheck_path"] = health
        entry["domains"] = self._domains(unit, service, level, base, name)
        self._routes(unit, access, base, mode, entry)
        middleware = self._middleware(unit, access, base)
        if middleware:
            entry["middleware"] = middleware
        self.services[name] = entry

    # ── image and build ─────────────────────────────────────────────────
    def _image(
        self, unit: _Unit, service: str, level: dict[str, Any], inherit: bool, base: str
    ) -> tuple[str | None, dict[str, Any] | None]:
        name = unit.containers[service]
        if service == "web":
            if "image" in unit.eff:
                return unit.eff["image"], None
            assert unit.build is not None
            return self._build(unit, service, unit.build, base, name)
        if "image" in level:
            return level["image"], None
        if "build" in level:
            return self._build(unit, service, level["build"], base, name)
        if not inherit:
            return self._build(unit, service, {}, base, name)
        if "image" in unit.eff:
            return unit.eff["image"], None
        # The service shares the main container's build. The main container is
        # emitted first, so its image (registry or adopted) is known here.
        self._todo(unit, base, "a service that shares the project build")
        web = unit.containers["web"]
        main_image = (self.services.get(web) or self.accessories.get(web) or {}).get("image")
        if main_image is not None:
            return main_image, None
        # The local build tag build_specs.yml:72 and git_deploy_image_prefix
        # derive. The prefix is the live tag on the boxes and stays until a
        # separate image migration.
        local = "argo-{{ stack_name }}-" + web + ":latest"  # kept-argo: live tag on boxes
        return local, None

    def _build(
        self, unit: _Unit, service: str, table: dict[str, Any], base: str, name: str
    ) -> tuple[str | None, dict[str, Any] | None]:
        where = _p(base, "build")
        repo = self._build_repo(unit, table, where)
        if repo is None:
            return None, None
        out: dict[str, Any] = {"repo": repo, "branch": unit.deploy.get("branch", "main")}
        strategy = table.get("strategy", self.defaults.get("build_strategy"))
        if strategy is not None:
            out["strategy"] = strategy
        for key in ("dockerfile", "context"):
            if key in table:
                out[key] = table[key]
        if table.get("args"):
            out["args"] = dict(table["args"])
        if table.get("secrets"):
            out["secrets"] = {k: _secret_ref(v) for k, v in table["secrets"].items()}
        paths: dict[str, list[str]] = {}
        if table.get("watch"):
            paths["include"] = list(table["watch"])
        if table.get("ignore"):
            paths["exclude"] = list(table["ignore"])
        if paths:
            out["paths"] = paths
        self._hold_keys(unit, out)
        token = self._repo_token(repo)
        if token is not None:
            out["token"] = _secret_ref(token)
        if "memory" in table and table["memory"] != self.defaults.get("build_memory"):
            self._todo(unit, _p(where, "memory"), "a build memory cap per project")

        image = unit.lock.images.get(service)
        if image is None and strategy in ("remote", "registry"):
            registry = self.defaults.get("registry")
            if registry is None:
                self._err(
                    f"{unit.label}: {where}: strategy {strategy} pushes to a registry, but "
                    "bay.fleet.toml sets no defaults.registry"
                )
            else:
                image = f"{registry}/{name}:latest"
        return image, out

    def _build_repo(self, unit: _Unit, table: dict[str, Any], where: str) -> str | None:
        """The repo a build clones: ``[build] repo``, then the lock ``repo``.

        ``[build] repo`` is for a project in the fleet (no app repo to ask). A
        project in its app repo builds from the lock ``repo``; a ``[build] repo``
        there must be the same repo, or the compile refuses.
        """
        from bay_cli import reposource

        declared = table.get("repo") or (unit.build or {}).get("repo")
        locked = unit.project.repo
        if declared is None:
            if locked is None:
                self._err(
                    f"{unit.label}: {where}: builds from source, but neither [build] repo in "
                    f"bay.toml nor projects/{unit.project.name}/bay.lock names a repo"
                )
            return locked
        if self._in_fleet(unit.project):
            return str(declared)
        if locked is not None and not reposource.same_repo(str(declared), locked):
            self._err(
                f"{unit.label}: {where}: [build] repo {declared} is not the repo of "
                f"projects/{unit.project.name}/bay.lock ({locked}); an app repo builds from "
                "its own repo, so remove [build] repo"
            )
            return None
        return locked if locked is not None else str(declared)

    def _in_fleet(self, project: Project) -> bool:
        """True when the project's bay.toml is ``projects/<name>/bay.toml`` in the fleet."""
        projects = (self.inputs.root / PROJECTS_DIR).resolve()
        return project.toml_file.resolve().is_relative_to(projects)

    def _hold_keys(self, unit: _Unit, out: dict[str, Any]) -> None:
        """The keys ``rebuild.sh`` reads to decide whether a push deploys.

        * ``track: pin`` when ``[deploy.<env>] track = "pin"`` (absent = branch).
        * ``frozen: true`` while ``bay rollback`` froze the environment.
        * ``bay_toml_hash`` and ``bay_toml_path`` when the bay.toml lives in the
          app repo, so a push can change it: the build side hashes the file at
          the pushed commit and holds the build when the hash differs. An
          in-fleet project's bay.toml is not in the app repo, so a push never
          changes its config and there is nothing to compare.
        * ``bay_toml_files`` next to them: every mount ``from`` of the project
          (``fleet:`` ones aside), relative to the repo root. A push that
          changes only these files and the bay.toml is config only: the build
          side neither builds nor deploys it (``bay up`` does).
        * ``bay_build_hash``: the hash of what the image is built from
          (``tomlhash.build_inputs``: ``[build]``, ``image`` and their
          per-env and per-service overrides). A push whose bay.toml changes
          it is never config only: it builds, and the hold guard holds it.

        Every key is left out at its default, so a fleet that uses none of
        this compiles byte-identically to before.
        """
        from bay_cli import bay_toml
        from bay_reconcile.tomlhash import canonical_hash, section_hash

        in_fleet = self._in_fleet(unit.project)
        if bay_toml.track(unit.doc, unit.env) == "pin":
            if in_fleet:
                self._err(
                    f"{unit.label}: deploy.{unit.env}.track: pin needs the bay.toml in the app "
                    "repo (the pin is an app repo commit); this project lives in the fleet"
                )
            out["track"] = "pin"
        if unit.lock.frozen:
            out["frozen"] = True
        if in_fleet or unit.project.lock is None:
            return
        try:
            data = unit.project.toml_file.read_bytes()
            out["bay_toml_hash"] = canonical_hash(data)
            out["bay_build_hash"] = section_hash(data, "build")
        except (OSError, ValueError) as exc:
            self._err(f"{unit.label}: cannot hash {unit.project.toml_file.name}: {exc}")
            return
        out["bay_toml_path"] = unit.project.lock.toml_path
        files = _repo_mount_paths(unit.project.doc, unit.project.lock.toml_path)
        if files:
            out["bay_toml_files"] = files

    def _repo_token(self, repo: str) -> str | None:
        tokens: dict[str, str] = self.fleet.get("repo_tokens", {})
        matches = [p for p in tokens if repo.startswith(p)]
        if not matches:
            return None
        return tokens[max(matches, key=len)]

    # ── env, secrets and needs ─────────────────────────────────────────
    def _env(
        self, unit: _Unit, service: str, level: dict[str, Any], inherit: bool, base: str
    ) -> tuple[dict[str, Any], dict[str, str] | None, set[str]]:
        doc = unit.doc
        name = unit.containers[service]
        is_web = service == "web"
        if is_web:
            clear = dict(unit.eff["env"])
            secrets = list(unit.eff.get("secrets", []))
            fleet_secrets = dict(doc.get("fleet_secrets", {}))
            needs = _needs(doc.get("needs"))
        elif inherit:
            clear = {**unit.eff["env"], **level.get("env", {})}
            secrets = list(dict.fromkeys([*unit.eff.get("secrets", []), *level.get("secrets", [])]))
            fleet_secrets = {**doc.get("fleet_secrets", {}), **level.get("fleet_secrets", {})}
            needs = {**_needs(doc.get("needs")), **_needs(level.get("needs"))}
        else:
            clear = dict(level.get("env", {}))
            secrets = list(level.get("secrets", []))
            fleet_secrets = dict(level.get("fleet_secrets", {}))
            needs = _needs(level.get("needs"))

        sources: dict[str, str] = {}

        def claim(var: str, source: str) -> None:
            if var in sources:
                self._err(f"{unit.label}: container {name}: {var} is set by both "
                          f"{sources[var]} and {source}")
            else:
                sources[var] = source

        for var in clear:
            claim(var, "env")
        for var in secrets:
            claim(var, "secrets")
        for var in fleet_secrets:
            claim(var, "fleet_secrets")

        database: dict[str, str] | None = None
        depends: set[str] = set()
        for need, opts in sorted(needs.items()):
            npath = _p(base, f"needs.{need}")
            alias = opts.get("env")
            if need == "postgres":
                res = self._find_resource(unit, "postgres", npath)
                if res is None:
                    continue
                db, user = self._db_names(unit)
                self._claim_database(unit, res, db, user)
                database = {"accessory": res, "name": db, "user": user}
                depends.add(res)
                for var in _DB_VARS:
                    claim(var, "needs.postgres")
                if alias:
                    claim(alias, "needs.postgres.env")
                    key = user.upper().replace("-", "_") + "_POSTGRES_PASSWORD"
                    clear[alias] = (
                        f"postgres://{user}:{{{{ secrets['{key}'] | urlencode }}}}"
                        f"@{res}:{_PG_PORT}/{db}"
                    )
                if opts.get("extensions"):
                    self._todo(unit, _p(npath, "extensions"), "postgres extensions")
                continue
            if need == "redis":
                res = self._find_resource(unit, "redis", npath)
                if res is None:
                    continue
                redis_url = f"redis://{res}:{self.resources[res].get('port', _REDIS_PORT)}"
                depends.add(res)
                for var in filter(None, ["REDIS_URL", alias]):
                    claim(var, f"needs.{need}")
                    clear[var] = redis_url
                continue
            url = self._need_url(unit, need, npath, depends)
            if url is None:
                continue
            # `env` names the variable instead of <NEED>_URL, so an app keeps
            # the name it reads today.
            var = alias or need.upper().replace("-", "_") + "_URL"
            claim(var, f"needs.{need}")
            clear[var] = url

        if inherit:
            for other, port in sorted(unit.ports.items()):
                if other == service:
                    continue
                var = sibling_var(other)
                claim(var, f"the {_svc_label(other)} URL")
                clear[var] = f"http://{unit.containers[other]}:{port}"

        env: dict[str, Any] = {}
        if clear:
            env["clear"] = dict(sorted(clear.items()))
        prefix = unit.secret_prefix
        if secrets and is_web and not fleet_secrets:
            env["secret"] = sorted(secrets)
        elif secrets or fleet_secrets:
            mapping = {var: f"{prefix}_{var}" for var in secrets}
            mapping.update(fleet_secrets)
            env["secret"] = dict(sorted(mapping.items()))
        return env, database, depends

    def _claim_database(self, unit: _Unit, res: str, db: str, user: str) -> None:
        owner = unit.label
        for table, key, what in (
            (self.databases, (res, db), "database"),
            (self.db_users, (res, user), "database user"),
        ):
            first = table.setdefault(key, owner)
            if first != owner:
                self._err(f"{what} {key[1]} on {res} is used by both {first} and {owner}")

    def _need_url(self, unit: _Unit, need: str, path: str, depends: set[str]) -> str | None:
        target = self.inputs.projects.get(need)
        if target is not None:
            if not target.doc.get("publish", False):
                self._err(f"{unit.label}: {path}: {need} does not set publish = true")
                return None
            tenv = unit.env if unit.env in target.doc["deploy"] else self.primary_env
            tunit = self.units.get((need, tenv))
            if tunit is None:
                self._err(
                    f"{unit.label}: {path}: {need} deploys neither {unit.env} nor "
                    f"{self.primary_env}"
                )
                return None
            port = tunit.ports.get("web")
            if port is None:
                self._err(f"{unit.label}: {path}: {need} has no port to reach")
                return None
            container = tunit.containers["web"]
            if tunit.box == unit.box:
                return f"http://{container}:{port}"
            ip = self.boxes[tunit.box].get("tailnet_ip")
            if ip is None:
                self._err(
                    f"{unit.label}: {path}: {need} runs on box {tunit.box}, which has no "
                    "tailnet_ip in bay.fleet.toml"
                )
                return None
            self.tailnet_exposed.add(container)
            return f"http://{ip}:{port}"
        res = self.resources.get(need)
        if res is not None and res.get("kind", "container") == "container":
            if unit.box not in self._resource_boxes(res):
                self._todo(unit, path, f"resource {need} on another box (cross-box access)")
                return None
            if "port" not in res:
                self._err(f"{unit.label}: {path}: resource {need} sets no port")
                return None
            depends.add(need)
            return f"http://{need}:{res['port']}"
        self._err(
            f"{unit.label}: {path}: {need} is neither a project in this fleet nor a "
            "resource in bay.fleet.toml"
        )
        return None

    # ── mounts ──────────────────────────────────────────────────────────
    def _mounts(
        self, unit: _Unit, level: dict[str, Any], base: str
    ) -> tuple[list[str], list[str], bool]:
        volumes: list[str] = []
        files: list[str] = []
        public = False
        for i, mount in enumerate(level.get("mounts", [])):
            mpath = _p(base, f"mounts[{i}]")
            if "volume" in mount:
                vname = self._volume_name(unit, mount["volume"])
                first = self.volumes.setdefault(vname, unit.label)
                if first != unit.label:
                    self._err(f"volume {vname} is used by both {first} and {unit.label}")
                volumes.append(f"{vname}:{mount['path']}")
                if "owner" in mount:
                    self._todo(unit, _p(mpath, "owner"), "a volume owner")
                if mount.get("backup", True):
                    self._todo(unit, _p(mpath, "backup"), "volume backups")
                continue
            src = mount["from"].rstrip("/")
            resolved = self._mount_source(unit, mpath, src)
            if resolved is None:
                continue
            target, listing = resolved
            if listing.is_dir():
                files.extend(
                    f"{target}/{p.relative_to(listing)}"
                    for p in sorted(listing.rglob("*")) if p.is_file()
                )
            else:
                files.append(target)
            dest = "{{ stack_dir }}/config/" + target
            volumes.append(f"{dest}:{mount['path']}:ro")
            if int(mount.get("mode", "0600"), 8) & 0o004:
                public = True
        return volumes, files, public

    def _mount_source(self, unit: _Unit, mpath: str, src: str) -> tuple[str, Path] | None:
        """``(target, path to list)`` of one ``from``: where it lands under config/ and files/.

        * ``fleet:<path>`` is the shared fleet file ``files/<path>``; the target is ``<path>``.
        * Any other ``from`` is relative to the directory of the bay.toml. The
          target is the adopted path from the lock, else ``<name>/<from>``.
          ``bay plan`` copies the file to ``files/<target>`` in its copy of the
          fleet. When the file is not beside the toml, the old place
          ``files/<name>/<from>`` is read, with a note (one release of
          overlap). An adopted ``files/<target>`` is not old: it is read first
          and gets no note.
        """
        root = self.inputs.root / FILES_DIR
        if src.startswith(FLEET_PREFIX):
            target = src[len(FLEET_PREFIX) :].strip("/")
            listing = root / target
            if not target or ".." in Path(target).parts or not listing.exists():
                self._err(
                    f"{unit.label} {mpath}: from = {src!r} cannot be listed, "
                    f"{FILES_DIR}/{target} in the fleet is not a file or a directory"
                )
                return None
            return target, listing
        adopted = unit.lock.files.get(src)
        target = adopted or f"{unit.project.name}/{src}"
        beside = unit.project.toml_file.parent / src
        old = root / target
        # An adopted path is today's files/<target>: it is listed first, as
        # the deploy copies it from there. ``bay plan`` maps a file beside the
        # toml onto it, so in its copy of the fleet the two are the same.
        if adopted and old.exists():
            return target, old
        if beside.exists():
            return target, beside
        if old.exists():
            if not adopted:
                self.notes.add(
                    f"{unit.project.name}: {FILES_DIR}/{target} is the old place of "
                    f"from = {src!r}; move it beside the bay.toml "
                    f"({self._toml_dir(unit)}/{src})"
                )
            return target, old
        self._err(
            f"{unit.label} {mpath}: from = {src!r} cannot be listed, "
            f"neither {FILES_DIR}/{target} nor {src} beside the bay.toml is a file "
            "or a directory"
        )
        return None

    def _toml_dir(self, unit: _Unit) -> str:
        directory = unit.project.toml_file.parent
        try:
            return str(directory.relative_to(self.inputs.root))
        except ValueError:
            pass
        if unit.project.lock is None:
            return f"{PROJECTS_DIR}/{unit.project.name}"
        parent = str(Path(unit.project.lock.toml_path).parent)
        return "the repo root" if parent == "." else f"the repo's {parent}"

    # ── routing ─────────────────────────────────────────────────────────
    def _domains(
        self, unit: _Unit, service: str, level: dict[str, Any], base: str, name: str
    ) -> list[str]:
        deploy = unit.deploy
        if service == "web":
            domain = deploy.get("domain", f"{unit.project.name}.{self.fleet['default_domain']}")
            aliases = list(deploy.get("aliases", []))
            if aliases and deploy.get("redirect", True):
                self._todo(
                    unit, f"deploy.{unit.env}.aliases",
                    "alias redirect (HTTP 308); the aliases are served instead",
                )
            domains = [domain, *aliases]
        else:
            override = deploy.get("services", {}).get(service, {})
            domains = [override.get("domain", level["domain"])]
        for d in domains:
            first = self.domains.setdefault(d, f"{unit.label} {_svc_label(service)}")
            if first != f"{unit.label} {_svc_label(service)}":
                self._err(f"domain {d} is used by both {first} and {unit.label} "
                          f"{_svc_label(service)}")
        return domains

    def _routes(
        self, unit: _Unit, access: dict[str, Any], base: str, mode: str, entry: dict[str, Any]
    ) -> None:
        open_paths = list(access.get("open", []))
        locked = list(access.get("locked", []))
        has_password = "password" in access
        for p in [*open_paths, *locked]:
            if not _ROUTE_RE.match(p):
                self._err(
                    f"{unit.label}: {_p(base, 'access')}: path {p} has a character a "
                    "route cannot hold; use letters, digits and . _ ~ % + / * -"
                )
        if mode == "public":
            if locked:
                entry["vpn_routes"] = locked
            if open_paths and has_password:
                self._todo(unit, _p(base, "access.open"), "open paths that skip the password")
        else:
            if open_paths:
                entry["public_routes"] = open_paths
                if has_password:
                    self._todo(
                        unit, _p(base, "access.open"), "open paths that skip the password"
                    )

    def _middleware(self, unit: _Unit, access: dict[str, Any], base: str) -> dict[str, Any]:
        mw: dict[str, Any] = {}
        limits = {**self.defaults.get("limits", {}), **access.get("limits", {})}
        if "rate" in limits or "burst" in limits:
            rl: dict[str, Any] = {}
            if "rate" in limits:
                amount, per = limits["rate"].split("/")
                rl["average"] = int(amount)
                rl["period"] = f"1{per}"
            if "burst" in limits:
                rl["burst"] = limits["burst"]
            mw["rate_limit"] = rl
        if "concurrent" in limits:
            mw["in_flight_req"] = {"amount": limits["concurrent"]}
        password = access.get("password")
        if password:
            creds = [
                {
                    "username": user,
                    "password": _secret_ref(f"{unit.secret_prefix}_PASSWORD_{user.upper()}"),
                }
                for user in password["users"]
            ]
            ba: dict[str, Any] = {"credentials": creds}
            if "realm" in password:
                ba["realm"] = password["realm"]
            mw["basic_auth"] = ba
        if "identity" in access:
            self._todo(unit, _p(base, "access.identity"), "the tailnet identity header")
        return mw

    # ── fleet-wide ──────────────────────────────────────────────────────
    def _tailnet_proxies(self) -> dict[str, dict[str, Any]]:
        proxies, errors = routes.compile_routes(self.fleet, self.domains)
        self.errors.extend(errors)
        hand = self.inputs.hand_tailnet
        if proxies and hand is not None:
            self._err(
                f"tailnet routes are defined in both bay.fleet.toml [tailnet.routes] and "
                f"{hand} (tailnet_proxies); run `bay route import` to move them, or "
                "delete the old file"
            )
        return proxies

    def _webhook(self) -> dict[str, str] | None:
        hook = self.fleet.get("webhook")
        if hook is None:
            return None
        by_group: dict[str, str] = {}
        for box, entry in sorted(self.boxes.items()):
            override = entry.get("webhook_domain")
            if override is None:
                continue
            group = entry.get("group")
            if group is None:
                self._err(
                    f"boxes.{box}.webhook_domain: box {box} has no group; "
                    "set group so the receiver on this box can pick its domain"
                )
            elif by_group.setdefault(group, override) != override:
                self._err(
                    f"boxes.{box}.webhook_domain: group {group} already has webhook domain "
                    f"{by_group[group]}; boxes of one group share one domain"
                )
        for domain in [hook["domain"], *by_group.values()]:
            first = self.domains.get(domain)
            if first is not None:
                self._err(f"domain {domain} is used by both {first} and the webhook")
        secret = _secret_ref(hook["secret"])
        if not by_group:
            return {"domain": hook["domain"], "secret": secret}
        # One shared file, one domain per box: the group of the box picks it.
        table = ", ".join(f"'{g}': '{d}'" for g, d in sorted(by_group.items()))
        pick = (
            f"{{{{ {{{table}}} | dict2items | selectattr('key', 'in', group_names) "
            f"| map(attribute='value') | first | default('{hook['domain']}') }}}}"
        )
        return {"domain": pick, "secret": secret}


# ── helpers ─────────────────────────────────────────────────────────────────


def _repo_mount_paths(doc: dict[str, Any], toml_path: str) -> list[str]:
    """Every mount ``from`` of ``doc`` relative to the repo root, sorted; ``fleet:`` ones aside.

    ``from`` is relative to the directory of the bay.toml (``toml_path``).
    """
    levels = [doc, *(v for v in (doc.get("services") or {}).values() if isinstance(v, dict))]
    directory = Path(toml_path).parent.as_posix()
    out: set[str] = set()
    for level in levels:
        for mount in level.get("mounts") or []:
            src = mount.get("from") if isinstance(mount, dict) else None
            if not isinstance(src, str) or src.startswith(FLEET_PREFIX):
                continue
            src = src.rstrip("/")
            out.add(src if directory in ("", ".") else f"{directory}/{src}")
    return sorted(out)


def _p(base: str, key: str) -> str:
    return f"{base}.{key}" if base else key


def _svc_label(service: str) -> str:
    return "main container" if service == "web" else f"service {service}"


def _secret_ref(name: str) -> str:
    return "{{ secrets." + name + " }}"


def _needs(value: Any) -> dict[str, dict[str, Any]]:
    if isinstance(value, list):
        return {n: {} for n in value}
    if isinstance(value, dict):
        return {k: dict(v or {}) for k, v in value.items()}
    return {}


def _log_retention(logs: str) -> dict[str, int] | None:
    if logs == "off":
        return None
    amount, unit = int(logs[:-1]), logs[-1]
    days = {"h": -(-amount // 24), "d": amount, "w": amount * 7}[unit]
    return {"days": days}


def default_output(fleet_root: Path) -> Path:
    from bay_cli.fleet import GENERATED_SERVICES

    return fleet_root / GENERATED_SERVICES
