"""Both `bin/bay` writers emit identical content.

`bootstrap.sh` and `bay setup` (`_ensure_bin_wrapper`) each create the
consumer's `bin/bay`, and both guard on "does it already exist" — so whichever
ran first won. They had already drifted: only the bootstrap version unset
`VIRTUAL_ENV`, and the two printed different missing-framework hints. Both now
copy `scripts/bin-bay-wrapper.sh` verbatim; this pins that.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from bay_cli.commands.framework import (
    WRAPPER_SOURCE,
    _ensure_bin_wrapper,
    _is_bay_boilerplate_wrapper,
)

_REPO_ROOT = Path(__file__).resolve().parent.parent
_WRAPPER = _REPO_ROOT / WRAPPER_SOURCE


def test_wrapper_source_exists_and_is_executable() -> None:
    assert _WRAPPER.is_file(), f"{WRAPPER_SOURCE} is the single source of truth"
    assert _WRAPPER.stat().st_mode & 0o111, "the wrapper source must be executable"


def test_wrapper_source_is_valid_bash() -> None:
    subprocess.run(["bash", "-n", str(_WRAPPER)], check=True)


def test_wrapper_unsets_virtualenv_and_execs_uv() -> None:
    text = _WRAPPER.read_text()
    # An inherited VIRTUAL_ENV makes `uv run --project .bay` warn and, in some
    # shells, resolve the wrong interpreter.
    assert "unset VIRTUAL_ENV" in text
    assert 'exec uv run --project "${SCRIPT_DIR}/.bay" bay "$@"' in text


def test_wrapper_hint_names_the_one_entry_path() -> None:
    """A missing .bay/ cannot be fixed by `make bay:setup` alone in every layout."""
    text = _WRAPPER.read_text()
    assert ".bay/bootstrap.sh" in text
    assert "make bay:setup" not in text


def test_bootstrap_copies_the_shared_wrapper() -> None:
    text = (_REPO_ROOT / "bootstrap.sh").read_text()
    assert f'WRAPPER_SRC="$BAY_DIR/{WRAPPER_SOURCE}"' in text, (
        "bootstrap.sh must copy the shared wrapper, not inline its own copy"
    )
    assert "<<'WRAPPER'" not in text, "bootstrap.sh still has an inline wrapper heredoc"


def test_bootstrap_snapshots_the_wrapper_before_pinning() -> None:
    """The pin rewinds the tree under the running script.

    bootstrap.sh executes from the clone's HEAD, then checks out `.bay-version`
    (or the newest tag). A tag older than scripts/bin-bay-wrapper.sh leaves
    nothing to copy — `cp: cannot stat`. The snapshot must therefore be taken
    before the checkout, and the fallbacks must be ordered snapshot → checked-out
    copy → error.
    """
    text = (_REPO_ROOT / "bootstrap.sh").read_text()
    snapshot = text.index('WRAPPER_SNAPSHOT="$(mktemp)"')
    checkout = text.index("git -C .bay -c advice.detachedHead=false checkout")
    write = text.index("chmod +x bin/bay")
    assert snapshot < checkout < write, (
        "the wrapper must be snapshotted before the version pin checks out a tag"
    )
    assert 'cp "$WRAPPER_SNAPSHOT" bin/bay' in text
    assert 'elif [ -f "$WRAPPER_SRC" ]; then' in text
    assert "wrapper source not found" in text


def test_ensure_bin_wrapper_writes_the_shared_wrapper(tmp_path: Path) -> None:
    root = tmp_path / "consumer"
    root.mkdir()
    _ensure_bin_wrapper(root, _REPO_ROOT)
    written = root / "bin" / "bay"
    assert written.read_text() == _WRAPPER.read_text()
    assert written.stat().st_mode & 0o111


# ── Existing-wrapper handling ────────────────────────────────────────────
# The wrapper Bay shipped to every real consumer. Inlined on purpose: the
# detector must classify the file that is actually out in the field, and a test
# that reads a sibling repo would only pass on one machine.
_REAL_CONSUMER_WRAPPER = """#!/usr/bin/env bash
# Bay CLI wrapper — rewritten by 'bay migrate-consumer'
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [ ! -d "${SCRIPT_DIR}/.bay" ]; then
  echo "Error: .bay/ directory not found." >&2
  echo "Run 'make bay:setup' to bootstrap the framework first." >&2
  exit 1
fi
unset VIRTUAL_ENV 2>/dev/null
exec uv run --project "${SCRIPT_DIR}/.bay" bay "$@"
"""

#: The pre-1.0 CLI name. Spelled once, so the rest of this file can talk about
#: the old wrapper without scattering the retired name through the tree.
_OLD = "argo"  # legacy-argo

_LEGACY_ERA_WRAPPER = f"""#!/usr/bin/env bash
# {_OLD.capitalize()} CLI wrapper — generated by bootstrap.sh
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/.." && pwd)"
if [ ! -d "${{SCRIPT_DIR}}/.{_OLD}" ]; then
  echo "Error: .{_OLD}/ directory not found." >&2
  exit 1
fi
unset VIRTUAL_ENV
exec uv run --project "${{SCRIPT_DIR}}/.{_OLD}" {_OLD} "$@"
"""

_HAND_EDITED_WRAPPER = _REAL_CONSUMER_WRAPPER.replace(
    "set -euo pipefail\n",
    "set -euo pipefail\nexport FOO=bar\n",
)


def _write_wrapper(root: Path, text: str) -> Path:
    wrapper = root / "bin" / "bay"
    wrapper.parent.mkdir(parents=True, exist_ok=True)
    wrapper.write_text(text)
    return wrapper


def test_shipped_wrapper_is_its_own_boilerplate() -> None:
    """The detector must recognise the file Bay ships, or nothing updates."""
    assert _is_bay_boilerplate_wrapper(_WRAPPER.read_text())


def test_real_consumer_wrapper_is_boilerplate() -> None:
    assert _is_bay_boilerplate_wrapper(_REAL_CONSUMER_WRAPPER)


def test_legacy_era_wrapper_is_boilerplate() -> None:
    """A consumer that never migrated still gets its wrapper refreshed."""
    assert _is_bay_boilerplate_wrapper(_LEGACY_ERA_WRAPPER)


def test_hand_edited_wrapper_is_not_boilerplate() -> None:
    assert not _is_bay_boilerplate_wrapper(_HAND_EDITED_WRAPPER)


def test_missing_marker_is_not_boilerplate() -> None:
    """Body alone is not enough. Without the header the file is not ours."""
    text = "\n".join(
        line
        for line in _REAL_CONSUMER_WRAPPER.splitlines()
        if "CLI wrapper" not in line
    )
    assert not _is_bay_boilerplate_wrapper(text)


def test_identical_wrapper_is_left_untouched(tmp_path: Path) -> None:
    root = tmp_path / "consumer"
    root.mkdir()
    wrapper = _write_wrapper(root, _WRAPPER.read_text())
    before = wrapper.stat().st_mtime_ns
    _ensure_bin_wrapper(root, _REPO_ROOT)
    assert wrapper.read_text() == _WRAPPER.read_text()
    assert wrapper.stat().st_mtime_ns == before


def test_stale_boilerplate_wrapper_is_updated(tmp_path: Path) -> None:
    root = tmp_path / "consumer"
    root.mkdir()
    wrapper = _write_wrapper(root, _REAL_CONSUMER_WRAPPER)
    _ensure_bin_wrapper(root, _REPO_ROOT)
    assert wrapper.read_text() == _WRAPPER.read_text()
    assert wrapper.stat().st_mode & 0o111


def test_hand_edited_wrapper_is_left_byte_identical(tmp_path: Path) -> None:
    root = tmp_path / "consumer"
    root.mkdir()
    wrapper = _write_wrapper(root, _HAND_EDITED_WRAPPER)
    _ensure_bin_wrapper(root, _REPO_ROOT)
    assert wrapper.read_text() == _HAND_EDITED_WRAPPER
