"""`bay compile`: fleet file + pinned bay.toml files -> services.yml.

The fixture fleet is tests/fixtures/fleet_min: two boxes, shared postgres and
redis, `shop` pinned by a lockfile with a local checkout (checkouts/shop) and
`gatus` living in the fleet (projects/gatus). Every test compiles a copy in
tmp_path, so the fixture itself is never written.

The gate at the bottom feeds the compiled file to today's validation (the
services JSON schema plus the `bay validate` cross checks) and to the
reconciler's own spec builder, roles/container_lifecycle/tasks/build_specs.yml.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest
import yaml
from typer.testing import CliRunner

from bay_cli import compiler
from bay_cli.cli import app
from bay_cli.fleet import GENERATED_SERVICES, FleetError, load_inputs

ROOT = Path(__file__).resolve().parent.parent
FIXTURE = ROOT / "tests" / "fixtures" / "fleet_min"
SHOP = Path("checkouts") / "shop" / "bay.toml"
GATUS = Path("projects") / "gatus" / "bay.toml"
FLEET = Path("bay.fleet.toml")
LOCK = Path("projects") / "shop.lock"

BANNED = re.compile(
    r"\b(accessor(y|ies)|rigs?|regions?|placements?|group_vars|inventor(y|ies)|playbooks?"
    r"|roles?|reconcilers?|consumers?|snapshots?|vaults?|stacks?|hosts?)\b",
    re.IGNORECASE,
)

runner = CliRunner()


# ── helpers ──────────────────────────────────────────────────────────────────


@pytest.fixture
def fleet(tmp_path: Path) -> Path:
    dest = tmp_path / "fleet"
    shutil.copytree(FIXTURE, dest)
    return dest


def edit(root: Path, rel: Path, old: str, new: str) -> None:
    path = root / rel
    text = path.read_text()
    assert old in text, f"{old!r} not in {rel}"
    path.write_text(text.replace(old, new, 1))


def edit_lock(root: Path, change: Any) -> None:
    path = root / LOCK
    data = json.loads(path.read_text())
    change(data)
    path.write_text(json.dumps(data, indent=2))


def compiled(root: Path) -> compiler.CompileResult:
    return compiler.compile_fleet(load_inputs(root))


def problems(root: Path) -> list[str]:
    with pytest.raises((compiler.CompileError, FleetError)) as info:
        compiled(root)
    return list(info.value.lines)


def todo_features(root: Path) -> set[str]:
    return {u.feature for u in compiled(root).unsupported}


def cli(root: Path, *args: str) -> Any:
    return runner.invoke(app, ["compile", "--fleet", str(root), *args])


def said(result: Any) -> str:
    """Everything a person sees: output, plus a BayError and its hint (main() prints those)."""
    exc = result.exception
    extra = f"\n{exc}\n{getattr(exc, 'hint', '') or ''}" if exc and not isinstance(exc, SystemExit) else ""
    return result.output + extra


@pytest.fixture(scope="module")
def data(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Any]:
    root = tmp_path_factory.mktemp("compiled") / "fleet"
    shutil.copytree(FIXTURE, root)
    result = compiled(root)
    assert result.unsupported == []
    return yaml.safe_load(result.body())


# ── determinism, header, hand edits, --check ────────────────────────────────


def test_compile_is_deterministic(fleet: Path, tmp_path: Path) -> None:
    first = compiled(fleet).text()
    second = compiled(fleet).text()
    assert first == second
    a, b = tmp_path / "a", tmp_path / "b"
    assert cli(fleet, "--out", str(a)).exit_code == 0
    assert cli(fleet, "--out", str(b)).exit_code == 0
    assert (a / GENERATED_SERVICES).read_bytes() == (b / GENERATED_SERVICES).read_bytes()
    assert (a / GENERATED_SERVICES).read_text() == first


def test_header_hash_verifies(fleet: Path) -> None:
    text = compiled(fleet).text()
    first_line = text.split("\n", 1)[0]
    assert first_line.startswith("# GENERATED by bay compile. sha256:")
    assert first_line.endswith("Do not edit; edit bay.toml or bay.fleet.toml.")
    digest, body = compiler.split_header(text)
    assert digest is not None and digest == compiler.body_digest(body)
    assert body.startswith("---\n")


def test_compile_writes_into_the_fleet_by_default(fleet: Path) -> None:
    result = cli(fleet, "--adopt")
    assert result.exit_code == 0, result.output
    assert (fleet / GENERATED_SERVICES).read_text() == compiled(fleet).text()
    again = cli(fleet)
    assert again.exit_code == 0 and "up to date" in again.output


def test_compile_refuses_hand_edited_output(fleet: Path, tmp_path: Path) -> None:
    out = tmp_path / "out"
    assert cli(fleet, "--out", str(out)).exit_code == 0
    target = out / GENERATED_SERVICES
    target.write_text(target.read_text().replace("redis:7", "redis:8"))
    edited = target.read_text()

    refused = cli(fleet, "--out", str(out))
    assert refused.exit_code != 0
    assert "edited by hand" in said(refused)
    assert target.read_text() == edited, "a refused compile must not write"

    forced = cli(fleet, "--out", str(out), "--force")
    assert forced.exit_code == 0
    assert target.read_text() == compiled(fleet).text()


def test_compile_refuses_a_file_it_did_not_write(fleet: Path) -> None:
    target = fleet / GENERATED_SERVICES
    target.write_text("---\nservices: {}\n")
    refused = cli(fleet)
    assert refused.exit_code != 0
    assert "not written by bay compile" in said(refused)
    assert "--adopt" in said(refused)
    assert cli(fleet, "--adopt").exit_code == 0
    assert compiler.split_header(target.read_text())[0] is not None


def test_check_prints_a_diff_and_exits_1(fleet: Path, tmp_path: Path) -> None:
    out = tmp_path / "out"
    missing = cli(fleet, "--out", str(out), "--check")
    assert missing.exit_code == 1
    assert not (out / GENERATED_SERVICES).exists(), "--check never writes"

    assert cli(fleet, "--out", str(out)).exit_code == 0
    clean = cli(fleet, "--out", str(out), "--check")
    assert clean.exit_code == 0

    edit(fleet, FLEET, 'image = "redis:7"', 'image = "redis:8"')
    drift = cli(fleet, "--out", str(out), "--check")
    assert drift.exit_code == 1
    assert "-    image: redis:7" in drift.output
    assert "+    image: redis:8" in drift.output


# ── mapping rows ─────────────────────────────────────────────────────────────


def test_container_names_follow_the_naming_rule(data: dict[str, Any]) -> None:
    assert set(data["services"]) == {
        "gatus", "shop", "shop-api", "shop-staging", "shop-staging-api",
    }
    assert {"shop-warmer", "shop-staging-warmer"} <= set(data["accessories"])


def test_access_modes(data: dict[str, Any]) -> None:
    s = data["services"]
    assert s["shop"]["access"] == "public"
    assert s["gatus"]["access"] == "vpn"
    # [deploy.staging] access.mode = "tailnet" overrides the top level
    assert s["shop-staging"]["access"] == "vpn"
    # internal = no router: an unrouted container is an accessories entry
    warmer = data["accessories"]["shop-warmer"]
    assert "domains" not in warmer and "access" not in warmer


def test_open_and_locked_paths(data: dict[str, Any]) -> None:
    s = data["services"]
    assert s["shop"]["vpn_routes"] == ["/admin"]
    assert s["gatus"]["public_routes"] == ["/api/v1/endpoints"]
    assert s["shop-api"]["public_routes"] == ["/webhooks"]
    # locked on a tailnet container is already tailnet-only
    assert "vpn_routes" not in s["shop-staging"]


def test_domain_and_aliases(data: dict[str, Any]) -> None:
    s = data["services"]
    assert s["shop"]["domains"] == ["shop.example.com", "www.shop.example.com"]
    assert s["shop-api"]["domains"] == ["api.shop.example.com"]
    assert s["shop-staging-api"]["domains"] == ["api-staging.shop.example.com"]


def test_default_domain_is_name_dot_fleet_domain(fleet: Path) -> None:
    edit(fleet, GATUS, 'domain = "status.example.com"\n', "")
    out = yaml.safe_load(compiled(fleet).body())
    assert out["services"]["gatus"]["domains"] == ["gatus.example.com"]


def test_image_and_build(data: dict[str, Any]) -> None:
    s = data["services"]
    assert s["gatus"]["image"] == "twinproduction/gatus:latest"
    assert "build" not in s["gatus"]
    build = s["shop"]["build"]
    assert build == {
        "repo": "git@github.com:acme/shop.git",
        "branch": "main",
        "strategy": "remote",
        "dockerfile": "Dockerfile",
        "args": {"NODE_ENV": "production"},
        "secrets": {"npmrc": "{{ secrets.NPMRC }}"},
        "paths": {"include": ["src/**", "package.json"], "exclude": ["*.md"]},
        "token": "{{ secrets.ACME_GIT_TOKEN }}",
    }
    # adopted image (production) vs registry-derived image (staging)
    assert s["shop"]["image"] == "registry.example.com/minfleet/shop-web:latest"
    assert s["shop-staging"]["image"] == "registry.example.com/minfleet/shop-staging:latest"
    assert s["shop-staging"]["build"]["branch"] == "develop"
    # an inline service build inherits nothing from [build]
    api = s["shop-api"]["build"]
    assert api["dockerfile"] == "apps/api/Dockerfile" and api["context"] == "apps/api"
    assert api["strategy"] == "local" and "args" not in api and "secrets" not in api
    assert "image" not in s["shop-api"], "a local build needs no registry image"


def test_build_args_merge_per_environment(fleet: Path) -> None:
    edit(fleet, SHOP, '[deploy.staging.env]', '[deploy.staging.build.args]\nDEBUG = "1"\n\n[deploy.staging.env]')
    out = yaml.safe_load(compiled(fleet).body())
    assert out["services"]["shop-staging"]["build"]["args"] == {"NODE_ENV": "production", "DEBUG": "1"}
    assert out["services"]["shop"]["build"]["args"] == {"NODE_ENV": "production"}


def test_fleet_default_build_strategy(fleet: Path) -> None:
    edit(fleet, SHOP, 'strategy = "remote"\nmemory', "memory")
    out = yaml.safe_load(compiled(fleet).body())
    assert out["services"]["shop-staging"]["build"]["strategy"] == "local"
    assert "image" not in out["services"]["shop-staging"]


def test_ports_health_memory_logs(data: dict[str, Any]) -> None:
    s = data["services"]
    assert s["shop"]["ports"]["internal"] == 3000
    assert s["shop-api"]["ports"] == {"internal": 4000}
    assert s["shop"]["healthcheck_path"] == "/healthz"
    assert s["shop-api"]["healthcheck_path"] == "/health"
    assert "healthcheck_path" not in s["gatus"], 'health = "none" sets no probe path'
    assert all("healthcheck" not in svc for svc in s.values())
    # swap-off ships in 2.x: memory sets only the memory limit today
    assert s["shop"]["mem_limit"] == "512m" and "memswap_limit" not in s["shop"]
    assert s["shop"]["log_retention"] == {"days": 7}
    assert "log_retention" not in s["gatus"], "fleet default logs = off"


@pytest.mark.parametrize(("logs", "days"), [("12h", 1), ("36h", 2), ("2w", 14)])
def test_log_units(fleet: Path, logs: str, days: int) -> None:
    edit(fleet, SHOP, 'logs = "7d"', f'logs = "{logs}"')
    out = yaml.safe_load(compiled(fleet).body())
    assert out["services"]["shop"]["log_retention"] == {"days": days}


def test_update_zero_downtime_replicas_command(data: dict[str, Any]) -> None:
    s, a = data["services"], data["accessories"]
    assert s["shop"]["update"] == "auto"
    assert s["shop-api"]["update"] is False
    assert s["shop"]["zero_downtime"] is True and "zero_downtime" not in s["shop-api"]
    assert s["shop-api"]["replicas"] == 2 and "replicas" not in s["shop"]
    assert s["shop"]["command"] == "node server.js"
    assert a["shop-warmer"]["command"] == "warm --every 5m"


def test_update_notify_is_the_default(fleet: Path) -> None:
    edit(fleet, GATUS, 'update = "auto"', 'update = "notify"')
    out = yaml.safe_load(compiled(fleet).body())
    assert "update" not in out["services"]["gatus"]


def test_env_secrets_and_fleet_secrets(data: dict[str, Any]) -> None:
    s = data["services"]
    shop = s["shop"]["env"]
    assert shop["clear"]["LOG_LEVEL"] == "info"
    assert s["shop-staging"]["env"]["clear"]["LOG_LEVEL"] == "debug"
    # secrets are names; the secret key is <MAIN CONTAINER>_<NAME> per environment
    assert shop["secret"] == {
        "SESSION_SECRET": "SHOP_SESSION_SECRET",
        "TURNSTILE_SECRET_KEY": "TURNSTILE_SECRET_KEY",
    }
    assert s["shop-staging"]["env"]["secret"]["SESSION_SECRET"] == "SHOP_STAGING_SESSION_SECRET"
    # a service reads the project's secret, not one of its own
    assert s["shop-api"]["env"]["secret"]["SESSION_SECRET"] == "SHOP_SESSION_SECRET"
    assert s["gatus"]["env"]["secret"] == {"TELEGRAM_BOT_TOKEN": "TELEGRAM_BOT_TOKEN"}


def test_secrets_use_the_list_form_on_the_main_container(fleet: Path) -> None:
    edit(fleet, SHOP, '[fleet_secrets]\nTURNSTILE_SECRET_KEY = "TURNSTILE_SECRET_KEY"\n', "")
    out = yaml.safe_load(compiled(fleet).body())
    assert out["services"]["shop"]["env"]["secret"] == ["SESSION_SECRET"]


def test_needs_postgres(data: dict[str, Any]) -> None:
    s = data["services"]
    # adopted names win in production; derived names elsewhere
    assert s["shop"]["database"] == {"accessory": "postgres", "name": "shop_prod", "user": "shop_app"}
    assert s["shop-staging"]["database"] == {
        "accessory": "postgres", "name": "shop_staging", "user": "shop_staging",
    }
    assert s["shop"]["env"]["clear"]["SHOP_DATABASE_URL"] == (
        "postgres://shop_app:{{ secrets['SHOP_APP_POSTGRES_PASSWORD'] | urlencode }}"
        "@postgres:5432/shop_prod"
    )
    assert "postgres" in s["shop"]["depends_on"]


def test_primary_database_name_is_the_project_name(fleet: Path) -> None:
    edit_lock(fleet, lambda d: d["envs"]["production"]["adopted"].pop("database"))
    edit_lock(fleet, lambda d: d["envs"]["production"]["adopted"].pop("role"))
    out = yaml.safe_load(compiled(fleet).body())
    assert out["services"]["shop"]["database"] == {
        "accessory": "postgres", "name": "shop", "user": "shop",
    }


def test_needs_redis(data: dict[str, Any]) -> None:
    shop = data["services"]["shop"]
    assert shop["env"]["clear"]["REDIS_URL"] == "redis://redis:6379"
    assert shop["depends_on"] == ["postgres", "redis"]


def test_needs_a_published_project_across_boxes(data: dict[str, Any]) -> None:
    s = data["services"]
    # gatus runs on na-1, shop on eu-1: reach shop over the tailnet
    assert s["gatus"]["env"]["clear"]["SHOP_URL"] == "http://100.64.0.3:3000"
    assert s["shop"]["ports"]["expose"] == "tailnet"
    assert "expose" not in s["shop-staging"]["ports"]


def test_needs_a_published_project_on_the_same_box(fleet: Path) -> None:
    edit(fleet, GATUS, 'box = "na-1"', 'box = "eu-1"')
    out = yaml.safe_load(compiled(fleet).body())
    assert out["services"]["gatus"]["env"]["clear"]["SHOP_URL"] == "http://shop:3000"
    assert "expose" not in out["services"]["shop"]["ports"]


def test_need_env_names_the_variable_instead(fleet: Path) -> None:
    edit(fleet, GATUS, 'needs = ["shop"]', 'needs = { shop = { env = "SHOP_BASE_URL" } }')
    clear = yaml.safe_load(compiled(fleet).body())["services"]["gatus"]["env"]["clear"]
    assert clear["SHOP_BASE_URL"] == "http://100.64.0.3:3000"
    assert "SHOP_URL" not in clear


def test_expose_publishes_the_container_port(fleet: Path) -> None:
    edit(fleet, SHOP, 'command = "warm --every 5m"', 'command = "warm --every 5m"\nexpose = "loopback"')
    edit(fleet, GATUS, "port = 8080", 'port = 8080\nexpose = "tailnet"')
    result = compiled(fleet)
    assert result.unsupported == []
    out = yaml.safe_load(result.body())
    assert out["accessories"]["shop-warmer"]["port"] == "9000:9000"
    assert "expose" not in out["accessories"]["shop-warmer"], "loopback is the default"
    assert out["services"]["gatus"]["ports"] == {"internal": 8080, "expose": "tailnet"}


def test_log_rotation(fleet: Path) -> None:
    edit(fleet, GATUS, 'update = "auto"', 'update = "auto"\nlog_rotation = { max_size = "10m", max_file = 2 }')
    out = yaml.safe_load(compiled(fleet).body())
    assert out["services"]["gatus"]["log_rotation"] == {"max_size": "10m", "max_file": 2}
    assert "log_rotation" not in out["services"]["shop"]


def test_adopted_files_keep_todays_config_path(fleet: Path) -> None:
    legal = fleet / "files" / "legal-site" / "beta"
    (legal / "de").mkdir(parents=True)
    (legal / "de" / "imprint.md").write_text("x\n")
    (legal / "terms.md").write_text("y\n")
    edit(fleet, SHOP, 'from = "deploy/config.yaml"', 'from = "legal"')
    edit_lock(fleet, lambda d: d["envs"]["production"]["adopted"].update(files={"legal": "legal-site/beta"}))
    out = yaml.safe_load(compiled(fleet).body())
    shop = out["services"]["shop"]
    assert "{{ stack_dir }}/config/legal-site/beta:/etc/shop/config.yaml:ro" in shop["volumes"]
    assert shop["config_files"] == ["legal-site/beta/de/imprint.md", "legal-site/beta/terms.md"]
    # staging adopts nothing: <name>/<from>
    assert out["services"]["shop-staging"]["config_files"] == ["shop/legal"]


def test_needs_an_unpublished_project_is_an_error(fleet: Path) -> None:
    edit(fleet, SHOP, "publish = true", "publish = false")
    assert any("does not set publish = true" in p for p in problems(fleet))


def test_sibling_urls(data: dict[str, Any]) -> None:
    s, a = data["services"], data["accessories"]
    assert s["shop"]["env"]["clear"]["API_URL"] == "http://shop-api:4000"
    assert s["shop"]["env"]["clear"]["WARMER_URL"] == "http://shop-warmer:9000"
    assert s["shop-api"]["env"]["clear"]["WEB_URL"] == "http://shop:3000"
    assert s["shop-staging"]["env"]["clear"]["API_URL"] == "http://shop-staging-api:4000"
    # inherit = false: no env at all, no sibling URLs
    assert "env" not in a["shop-warmer"]


def test_mounts(data: dict[str, Any]) -> None:
    s = data["services"]
    assert s["shop"]["volumes"] == [
        "shop_data:/app/data",
        "{{ stack_dir }}/config/shop/deploy/config.yaml:/etc/shop/config.yaml:ro",
    ]
    assert s["shop"]["config_files"] == ["shop/deploy/config.yaml"]
    assert s["shop"]["config_files_mode"] == "public"
    assert "shop-staging-data:/app/data" in s["shop-staging"]["volumes"]
    assert s["gatus"]["volumes"] == [
        "{{ stack_dir }}/config/gatus/config.yaml:/config/config.yaml:ro",
        "gatus-data:/data",
    ]
    assert "config_files_mode" not in s["gatus"], "mode 0600 stays private"


def test_from_directory_lists_every_file(fleet: Path) -> None:
    extra = fleet / "checkouts" / "shop" / "deploy" / "more"
    extra.mkdir()
    (extra / "b.yaml").write_text("b\n")
    (extra / "a.yaml").write_text("a\n")
    edit(fleet, SHOP, 'from = "deploy/config.yaml"', 'from = "deploy/more"')
    edit(fleet, SHOP, 'path = "/etc/shop/config.yaml"', 'path = "/etc/shop/more"')
    out = yaml.safe_load(compiled(fleet).body())
    assert out["services"]["shop"]["config_files"] == ["shop/deploy/more/a.yaml", "shop/deploy/more/b.yaml"]


def test_shared_volume_within_one_project(fleet: Path) -> None:
    edit(fleet, SHOP, 'memory = "128m"\n', 'memory = "128m"\nmounts = [{ path = "/srv/data", volume = "data", backup = false }]\n')
    out = yaml.safe_load(compiled(fleet).body())
    assert "shop_data:/srv/data" in out["accessories"]["shop-warmer"]["volumes"]


def test_limits_and_password(data: dict[str, Any]) -> None:
    s = data["services"]
    mw = s["shop"]["middleware"]
    assert mw["rate_limit"] == {"average": 100, "burst": 50, "period": "1s"}
    # fleet [defaults.limits] concurrent applies to every routed container
    assert mw["in_flight_req"] == {"amount": 100}
    assert s["gatus"]["middleware"] == {"in_flight_req": {"amount": 100}}
    assert mw["basic_auth"] == {
        "credentials": [{"username": "admin", "password": "{{ secrets.SHOP_PASSWORD_ADMIN }}"}],
        "realm": "Staff only",
    }
    # password is never inherited by a service
    assert "basic_auth" not in s["shop-api"]["middleware"]


def test_rate_per_minute(fleet: Path) -> None:
    edit(fleet, SHOP, 'rate = "100/s"', 'rate = "600/m"')
    out = yaml.safe_load(compiled(fleet).body())
    assert out["services"]["shop"]["middleware"]["rate_limit"]["period"] == "1m"


def test_resources_compile_to_accessories(data: dict[str, Any]) -> None:
    pg = data["accessories"]["postgres"]
    assert pg["image"] == "postgres:16"
    assert pg["port"] == "5432:5432" and "expose" not in pg
    assert pg["regions"] == ["eu", "na"]
    assert pg["env"] == {
        "clear": {"POSTGRES_DB": "app", "POSTGRES_USER": "app"},
        "secret": {"POSTGRES_PASSWORD": "POSTGRES_PASSWORD"},
    }
    assert pg["healthcheck"]["test"] == ["CMD", "pg_isready", "-U", "app"]
    assert pg["backup"]["method"] == "pg_dump"
    redis = data["accessories"]["redis"]
    assert redis == {"image": "redis:7", "mem_limit": "256m", "regions": ["eu"], "update": False}


def test_webhook_and_regions(data: dict[str, Any]) -> None:
    assert data["webhook"] == {"domain": "deploy.example.com", "secret": "{{ secrets.WEBHOOK_SECRET }}"}
    assert data["services"]["gatus"]["regions"] == ["na"]
    assert data["services"]["shop"]["regions"] == ["eu"]


def test_adopted_container_names_win(fleet: Path) -> None:
    edit_lock(fleet, lambda d: d["envs"]["production"]["adopted"].update(
        containers={"web": "shop-prod", "api": "shop-api-v1"}))
    out = yaml.safe_load(compiled(fleet).body())
    s = out["services"]
    assert "shop-prod" in s and "shop-api-v1" in s and "shop" not in s
    # secret keys and sibling URLs follow the adopted name
    assert s["shop-prod"]["env"]["secret"]["SESSION_SECRET"] == "SHOP_PROD_SESSION_SECRET"
    assert s["shop-prod"]["env"]["clear"]["API_URL"] == "http://shop-api-v1:4000"
    assert s["gatus"]["env"]["clear"]["SHOP_URL"] == "http://100.64.0.3:3000"


def test_internal_main_container_is_unrouted(fleet: Path) -> None:
    edit(fleet, GATUS, 'mode = "tailnet"\nopen = ["/api/v1/endpoints"]', 'mode = "internal"')
    edit(fleet, GATUS, 'domain = "status.example.com"\n', "")
    out = yaml.safe_load(compiled(fleet).body())
    assert "gatus" not in out["services"]
    assert out["accessories"]["gatus"]["image"] == "twinproduction/gatus:latest"


# ── collisions ───────────────────────────────────────────────────────────────


def _second_project(root: Path, name: str, body: str) -> None:
    d = root / "projects" / name
    d.mkdir()
    (d / "bay.toml").write_text(
        f'name = "{name}"\nfleet = "minfleet"\nimage = "nginx:1"\nport = 80\n{body}'
    )


def test_compile_collision_is_error(fleet: Path) -> None:
    _second_project(fleet, "blog", '[access]\nmode = "public"\n[deploy.production]\ndomain = "shop.example.com"\n')
    msgs = problems(fleet)
    assert any("domain shop.example.com is used by both" in m for m in msgs), msgs


def test_container_name_collision(fleet: Path) -> None:
    _second_project(fleet, "blog", '[access]\nmode = "public"\n[deploy.production]\ndomain = "blog.example.com"\n')
    (fleet / "projects" / "blog.lock").write_text(json.dumps({
        "lock_version": 1, "name": "blog", "repo": None, "commit": None,
        "envs": {"production": {"adopted": {"containers": {"web": "gatus"}}}},
    }))
    msgs = problems(fleet)
    assert any("container name gatus is used by both" in m for m in msgs), msgs


def test_container_name_collides_with_a_resource(fleet: Path) -> None:
    _second_project(fleet, "redis", '[access]\nmode = "public"\n[deploy.production]\ndomain = "r.example.com"\n')
    msgs = problems(fleet)
    assert any("container name redis is used by both resource redis" in m for m in msgs), msgs


def test_derived_router_name_collision(fleet: Path) -> None:
    _second_project(fleet, "shop-vpn", '[access]\nmode = "public"\n[deploy.production]\ndomain = "v.example.com"\n')
    msgs = problems(fleet)
    assert any("collides with the -vpn name" in m for m in msgs), msgs


def test_volume_collision(fleet: Path) -> None:
    edit_lock(fleet, lambda d: d["envs"]["production"]["adopted"].update(volumes={"data": "gatus-data"}))
    msgs = problems(fleet)
    assert any("volume gatus-data is used by both" in m for m in msgs), msgs


def test_database_collision(fleet: Path) -> None:
    _second_project(
        fleet, "blog",
        'needs = ["postgres"]\n[access]\nmode = "public"\n[deploy.production]\ndomain = "b.example.com"\n',
    )
    (fleet / "projects" / "blog.lock").write_text(json.dumps({
        "lock_version": 1, "name": "blog",
        "envs": {"production": {"adopted": {"database": "shop_prod", "role": "blog"}}},
    }))
    msgs = problems(fleet)
    assert any("database shop_prod on postgres is used by both" in m for m in msgs), msgs


def test_env_var_collision_in_one_container(fleet: Path) -> None:
    edit(fleet, SHOP, 'LOG_LEVEL = "info"', 'LOG_LEVEL = "info"\nDB_HOST = "elsewhere"')
    msgs = problems(fleet)
    assert any("DB_HOST is set by both env and needs.postgres" in m for m in msgs), msgs


def test_hand_maintained_key_collision(fleet: Path) -> None:
    (fleet / "group_vars" / "all" / "extra.yml").write_text(
        "---\naccessories:\n  redis:\n    image: redis:6\nsecret: !vault |\n  abc\n"
    )
    msgs = problems(fleet)
    assert any("redis" in m and "defined by hand in group_vars/all/extra.yml" in m for m in msgs)


def test_webhook_domain_collision(fleet: Path) -> None:
    edit(fleet, GATUS, 'domain = "status.example.com"', 'domain = "deploy.example.com"')
    assert any("and the webhook" in m for m in problems(fleet))


# ── unsupported features ─────────────────────────────────────────────────────


UNSUPPORTED = [
    pytest.param(SHOP, 'secrets = ["SESSION_SECRET"]', 'secrets = ["SESSION_SECRET"]\nrelease = "migrate"', "a release command before traffic moves", id="release"),
    pytest.param(SHOP, "[deploy.production]", '[[jobs]]\nname = "nightly"\nschedule = "0 2 * * *"\ncommand = "x"\n\n[deploy.production]', "scheduled jobs", id="jobs"),
    pytest.param(SHOP, 'volume = "data"\nbackup = false', 'volume = "data"\nbackup = false\nowner = "472:472"', "a volume owner", id="mount-owner"),
    pytest.param(SHOP, "redirect = false\n", "", "alias redirect (HTTP 308); the aliases are served instead", id="alias-redirect"),
    pytest.param(SHOP, "[deploy.production]", '[backup]\nkeep = "7d"\n\n[deploy.production]', "project backup schedule for volumes", id="project-backup"),
    pytest.param(SHOP, 'volume = "data"\nbackup = false', 'volume = "data"', "volume backups", id="volume-backup"),
    pytest.param(SHOP, 'realm = "Staff only"', 'realm = "Staff only"\n\n[access.identity]\nheader = "X-Tailnet-Device"', "the tailnet identity header", id="identity"),
    pytest.param(SHOP, 'env = "SHOP_DATABASE_URL"', 'env = "SHOP_DATABASE_URL"\nextensions = ["vector"]', "postgres extensions", id="pg-extensions"),
    pytest.param(SHOP, 'command = "warm --every 5m"', 'command = "warm --every 5m"\npath = "/warm"', "routing a service by path on the main domain", id="service-path"),
    pytest.param(SHOP, 'locked = ["/admin"]', 'locked = ["/admin"]\nopen = ["/hooks"]', "open paths that skip the password", id="open-with-password"),
    pytest.param(SHOP, 'memory = "2g"\nwatch', 'memory = "4g"\nwatch', "a build memory cap per project", id="build-memory"),
    pytest.param(SHOP, 'build = { dockerfile = "apps/api/Dockerfile", context = "apps/api", strategy = "local" }\n', "", "a service that shares the project build", id="shared-build"),
]


@pytest.mark.parametrize(("rel", "old", "new", "feature"), UNSUPPORTED)
def test_unsupported_feature_is_reported(fleet: Path, rel: Path, old: str, new: str, feature: str) -> None:
    edit(fleet, rel, old, new)
    assert feature in todo_features(fleet)


def test_unsupported_refuses_without_the_flag(fleet: Path, tmp_path: Path) -> None:
    edit(fleet, SHOP, "[deploy.production]", '[[jobs]]\nname = "nightly"\nschedule = "0 2 * * *"\ncommand = "x"\n\n[deploy.production]')
    out = tmp_path / "out"
    refused = cli(fleet, "--out", str(out))
    assert refused.exit_code != 0
    assert "# TODO(role) shop: jobs[0]: scheduled jobs" in refused.output
    assert not (out / GENERATED_SERVICES).exists()

    allowed = cli(fleet, "--out", str(out), "--allow-unsupported")
    assert allowed.exit_code == 0, allowed.output
    text = (out / GENERATED_SERVICES).read_text()
    assert "# TODO(role) shop: jobs[0]: scheduled jobs\n" in text
    digest, body = compiler.split_header(text)
    assert digest == compiler.body_digest(body)


def test_cross_box_database_is_unsupported(fleet: Path) -> None:
    edit(fleet, FLEET, 'box = ["eu-1", "na-1"]', 'box = "na-1"')
    assert "postgres on another box than eu-1 (cross-box data access)" in todo_features(fleet)


# ── input errors ─────────────────────────────────────────────────────────────


def test_fleet_file_unknown_key(fleet: Path) -> None:
    edit(fleet, FLEET, 'primary_env = "production"', 'primary_env = "production"\nflavour = "x"')
    assert any(m.startswith("bay.fleet.toml: flavour: unknown key") for m in problems(fleet))


def test_fleet_box_must_exist(fleet: Path) -> None:
    edit(fleet, GATUS, 'box = "na-1"', 'box = "us-9"')
    assert any("box us-9 is not in bay.fleet.toml [boxes]" in m for m in problems(fleet))


def test_project_fleet_must_match(fleet: Path) -> None:
    edit(fleet, GATUS, 'fleet = "minfleet"', 'fleet = "otherfleet"')
    assert any("but this fleet is minfleet" in m for m in problems(fleet))


def test_invalid_bay_toml_stops_compile(fleet: Path) -> None:
    edit(fleet, GATUS, "port = 8080", "port = 0")
    assert any(m.startswith("projects/gatus/bay.toml: port:") for m in problems(fleet))


def test_lockfile_checks(fleet: Path) -> None:
    edit_lock(fleet, lambda d: d.update(lock_version=2))
    assert any(m.startswith("projects/shop.lock: lock_version") for m in problems(fleet))


def test_lockfile_name_must_match_the_file(fleet: Path) -> None:
    edit_lock(fleet, lambda d: d.update(name="shoppe"))
    assert any("the file is named shop.lock" in m for m in problems(fleet))


def test_lockfile_env_must_exist_in_bay_toml(fleet: Path) -> None:
    edit_lock(fleet, lambda d: d["envs"].update(qa={"box": "eu-1"}))
    assert any("envs.qa: bay.toml has no [deploy.qa]" in m for m in problems(fleet))


def test_build_needs_a_repo(fleet: Path) -> None:
    edit_lock(fleet, lambda d: d.update(repo=None))
    assert any("names no repo" in m for m in problems(fleet))


def test_box_without_group_is_ambiguous(fleet: Path) -> None:
    edit(fleet, FLEET, 'group = "na"\n', "")
    assert any("box na-1 has no group" in m for m in problems(fleet))


def test_messages_use_no_banned_words(fleet: Path) -> None:
    """Every message a person sees, except the fixed TODO(role) marker."""
    samples = []
    for rel, old, new, _f in [p.values for p in UNSUPPORTED]:
        root = fleet.parent / f"u{len(samples)}"
        shutil.copytree(FIXTURE, root)
        edit(root, rel, old, new)
        samples.extend(u.feature for u in compiled(root).unsupported)
    for case in (
        lambda r: edit(r, SHOP, "publish = true", "publish = false"),
        lambda r: edit_lock(r, lambda d: d.update(repo=None)),
        lambda r: edit(r, FLEET, 'group = "na"\n', ""),
        lambda r: edit(r, GATUS, 'box = "na-1"', 'box = "us-9"'),
        lambda r: edit(r, SHOP, 'LOG_LEVEL = "info"', 'LOG_LEVEL = "info"\nDB_HOST = "x"'),
        lambda r: edit_lock(r, lambda d: d["envs"].update(qa={})),
    ):
        root = fleet.parent / f"e{len(samples)}"
        shutil.copytree(FIXTURE, root)
        case(root)
        samples.extend(problems(root))
    hits = [m for m in samples if BANNED.search(m)]
    assert hits == []


# ── THE GATE: today's validation and the reconciler's spec builder ───────────


def test_compiled_file_passes_todays_validation(data: dict[str, Any]) -> None:
    from bay_cli.commands import validate as v

    result = v.ValidationResult()
    plain = v._validate_services_schema(ROOT, {"group_vars/all/services.yml": data}, result)
    assert plain is not None
    v._validate_identifier_safety(plain, result)
    v._validate_reserved_names(plain, result)
    v._validate_memswap_limits(plain, result)
    v._check_domain_uniqueness(plain["services"], result)
    v._check_depends_on(plain["services"], plain["accessories"], result)
    assert result.failed == [], result.failed


def _secret_names(text: str, parsed: dict[str, Any]) -> set[str]:
    names = set(re.findall(r"secrets(?:\.|\[')([A-Z0-9_]+)", text))
    for block in (*parsed["services"].values(), *parsed["accessories"].values()):
        secret = block.get("env", {}).get("secret")
        if isinstance(secret, dict):
            names |= set(secret.values())
    return names


def test_compile_fixture_fleet_feeds_build_specs(fleet: Path, tmp_path: Path) -> None:
    """The reconciler's build_specs.yml (and env.j2) accept the compiled file."""
    text = compiled(fleet).text()
    parsed = yaml.safe_load(text)

    def active(block: dict[str, Any]) -> dict[str, Any]:
        return {k: v for k, v in block.items() if not v.get("regions") or "eu" in v["regions"]}

    shop = parsed["services"]["shop"]
    play_vars = {
        "stack_dir": str(tmp_path / "stack"),
        "stack_name": "minfleet",
        "secrets": {k: f"pw-{k.lower()}" for k in _secret_names(text, parsed)},
        "gateway_bind_ip": "100.64.0.3",
        "bay_alert_host": "eu-1",
        "services": parsed["services"],
        "accessories": parsed["accessories"],
        "webhook": parsed["webhook"],
        "active_services": active(parsed["services"]),
        "active_accessories": active(parsed["accessories"]),
        "env_service_name": "shop",
        "env_clear": shop["env"]["clear"],
        "env_secrets": shop["env"]["secret"],
        "env_database": shop["database"],
    }
    (tmp_path / "vars.json").write_text(json.dumps(play_vars))
    (tmp_path / "ansible.cfg").write_text("[defaults]\n")
    specs, env_file = tmp_path / "specs.json", tmp_path / "shop.env"
    (tmp_path / "play.yml").write_text(
        "- hosts: localhost\n"
        "  connection: local\n"
        "  gather_facts: false\n"
        "  tasks:\n"
        f"    - ansible.builtin.include_tasks: {ROOT / 'roles/container_lifecycle/tasks/build_specs.yml'}\n"
        "    - ansible.builtin.copy:\n"
        "        content: '{{ container_specs | to_nice_json }}'\n"
        f"        dest: {specs}\n"
        "        mode: '0600'\n"
        "    - ansible.builtin.template:\n"
        f"        src: {ROOT / 'roles/deploy_stack/templates/env.j2'}\n"
        f"        dest: {env_file}\n"
        "        mode: '0600'\n"
    )
    plugins = os.pathsep.join(
        [str(ROOT / "roles/container_lifecycle/filter_plugins"), str(ROOT / "filter_plugins")]
    )
    env = {
        **os.environ,
        "ANSIBLE_FILTER_PLUGINS": plugins,
        "ANSIBLE_CONFIG": str(tmp_path / "ansible.cfg"),
        "ANSIBLE_NOCOLOR": "1",
        "ANSIBLE_LOCALHOST_WARNING": "0",
        "ANSIBLE_INVENTORY_UNPARSED_WARNING": "0",
        "ANSIBLE_PYTHON_INTERPRETER": sys.executable,
    }
    proc = subprocess.run(
        [sys.executable, "-m", "ansible.cli.playbook", "-i", "localhost,",
         "-e", f"@{tmp_path / 'vars.json'}", str(tmp_path / "play.yml")],
        cwd=tmp_path, env=env, capture_output=True, text=True, timeout=300,
    )
    assert proc.returncode == 0, proc.stdout[-3000:] + proc.stderr[-3000:]

    by_name = {s["name"]: s for s in json.loads(specs.read_text())}
    expected = set(active(parsed["services"])) | set(active(parsed["accessories"]))
    assert expected <= set(by_name)
    assert "gatus" not in by_name, "gatus runs on the na box"
    assert by_name["shop"]["type"] == "service"
    assert by_name["shop"]["ports"] == ["100.64.0.3:3000:3000"]
    assert by_name["shop"]["mem_limit"] == "512m" and "memswap_limit" not in by_name["shop"]
    labels = by_name["shop"]["labels"]
    assert labels["traefik.http.routers.shop-health.rule"].startswith("(Host(`shop.example.com`)")
    assert "shop-basicauth" in labels["traefik.http.routers.shop.middlewares"]
    staging = by_name["shop-staging"]["labels"]
    assert "traefik.http.routers.shop-staging-vpn.rule" in staging, "tailnet compiles to vpn"
    assert by_name["shop-warmer"]["type"] == "accessory"
    assert by_name["postgres"]["ports"] == ["127.0.0.1:5432:5432"]

    lines = dict(
        line.split("=", 1) for line in env_file.read_text().splitlines()
        if line and not line.startswith("#")
    )
    assert lines["SHOP_DATABASE_URL"] == lines["DATABASE_URL"]
    assert lines["SESSION_SECRET"] == "pw-shop_session_secret"
    assert lines["WARMER_URL"] == "http://shop-warmer:9000"
