"""Tests for M78-S8: correlation ID end-to-end push tracing.

Verifies that:
1. Trigger files with two lines → CORR_ID set to line 1 (UUID)
2. Legacy single-line trigger files → CORR_ID set to "unknown"
3. No trigger file (manual invocation) → CORR_ID starts with "manual-"
4. All rebuild.sh log output includes [${CORR_ID:-no-corr}] prefix via _log()
5. notify_build auto-appends correlation ID footer when CORR_ID is set
   and not "unknown"

Known limitation: cross-region correlation. The corr_id generated by the
webhook receiver on region EU is written to EU's trigger file. When EU
fans out a push to NA via the forward mechanism, NA's webhook generates
its OWN corr_id for its trigger file. The corr_ids on EU and NA are
therefore different for the same push. Cross-region correlation currently
requires matching on the GitHub delivery ID (X-GitHub-Delivery header)
in the webhook logs, not the corr_id. This is documented as a known
limitation — fixing it would require forwarding the originator's corr_id
in the fanout request body.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

_TESTS_DIR = Path(__file__).resolve().parent
if str(_TESTS_DIR) not in sys.path:
    sys.path.insert(0, str(_TESTS_DIR))

from test_rebuild_config import _local_service, _render_rebuild_sh  # noqa: E402
from test_cb_state_schema import _extract_helper  # noqa: E402


_REBUILD_TEMPLATE = (
    Path(__file__).resolve().parent.parent
    / "roles"
    / "git_deploy"
    / "templates"
    / "rebuild.sh.j2"
)


def _make_local_service(svc_name: str, branch: str = "main") -> dict:
    """Build a single local service dict with the given name."""
    base = _local_service()
    # _local_service() returns {"localapp": {...}}; re-key to svc_name
    svc_data = list(base.values())[0]
    # Adjust the branch
    svc_data["build"]["branch"] = branch
    return {svc_name: svc_data}


def _render_for_corr_tests() -> str:
    """Render rebuild.sh with a minimal single local service."""
    svc_name = "localapp"
    svc = _local_service()
    return _render_rebuild_sh(
        svc,
        rebuild_services=[svc_name],
        git_deploy_services=[svc_name],
    )


def _extract_corr_block(rendered: str) -> str:
    """Extract the CORR_ID + PULL_SIGNAL detection block from rendered script.

    Extracts from the "# ── Read correlation ID" comment through the closing
    fi of the if/else block (stops before any subsequent _log/echo calls).
    """
    match = re.search(
        r"# ── Read correlation ID.*?^fi$",
        rendered,
        re.DOTALL | re.MULTILINE,
    )
    assert match is not None, "Could not find CORR_ID detection block in rendered script"
    return match.group(0)


def _run_corr_block(trigger_content: str | None, tmpdir: Path) -> dict:
    """Run the CORR_ID detection block with a given trigger file content.

    Returns dict with keys: corr_id, pull_signal, exit_code, stdout.
    """
    rendered = _render_for_corr_tests()

    triggers_dir = tmpdir / "triggers"
    triggers_dir.mkdir(parents=True, exist_ok=True)

    trigger_path = triggers_dir / "localapp.trigger"
    if trigger_content is not None:
        trigger_path.write_text(trigger_content)

    # Build a minimal bash script that sources the CORR_ID block and prints results
    script = f"""#!/usr/bin/env bash
set -euo pipefail
STACK_DIR="{tmpdir}"
SERVICE="localapp"
EPOCHSECONDS=$(date +%s)

{_extract_corr_block(rendered)}

echo "CORR_ID=${{CORR_ID}}"
echo "PULL_SIGNAL=${{PULL_SIGNAL}}"
"""
    script_path = tmpdir / "test_corr.sh"
    script_path.write_text(script)
    script_path.chmod(0o755)

    result = subprocess.run(
        ["bash", str(script_path)],
        capture_output=True,
        text=True,
    )

    output = result.stdout
    corr_id = ""
    pull_signal = ""
    for line in output.splitlines():
        if line.startswith("CORR_ID="):
            corr_id = line[len("CORR_ID="):]
        elif line.startswith("PULL_SIGNAL="):
            pull_signal = line[len("PULL_SIGNAL="):]

    return {
        "corr_id": corr_id,
        "pull_signal": pull_signal,
        "exit_code": result.returncode,
        "stdout": output,
        "stderr": result.stderr,
    }


# ── Template structure tests (no subprocess) ────────────────────────

def test_log_helper_in_template():
    """_log() helper must be present in the rendered template."""
    rendered = _render_for_corr_tests()
    assert "_log()" in rendered or "_log ()" in rendered, (
        "_log() function not found in rendered rebuild.sh"
    )


def test_log_helper_uses_corr_id_prefix():
    """_log() must embed [${CORR_ID:-no-corr}] in its echo."""
    rendered = _render_for_corr_tests()
    assert "${CORR_ID:-no-corr}" in rendered, (
        "_log() must use [${CORR_ID:-no-corr}] prefix so log lines are "
        "greppable by correlation ID"
    )


def test_notify_build_appends_corr_footer():
    """notify_build must append correlation ID footer when CORR_ID is set."""
    rendered = _render_for_corr_tests()
    # The footer append must be inside notify_build's body
    notify_build_fn = _extract_helper(rendered, "notify_build")
    assert "CORR_ID" in notify_build_fn, (
        "notify_build must reference CORR_ID to append the correlation footer"
    )
    assert "Correlation ID" in notify_build_fn or "corr" in notify_build_fn.lower(), (
        "notify_build must append a 'Correlation ID:' footer line"
    )


def test_trigger_format_v2_comment_present():
    """Template must document the 2-line trigger format."""
    content = _REBUILD_TEMPLATE.read_text()
    assert "line 1 = corr_id" in content or "Line 1 = corr_id" in content or "line 1" in content.lower(), (
        "Template must document the 2-line trigger file format"
    )


# ── Runtime behaviour tests (subprocess) ────────────────────────────

def test_two_line_trigger_corr_id_parsed(tmp_path):
    """2-line trigger file: CORR_ID set to line 1 (UUID)."""
    expected_id = "a3f9e1b2-1234-5678-abcd-000000000001"
    result = _run_corr_block(f"{expected_id}\npull", tmp_path)
    assert result["exit_code"] == 0, f"Script failed: {result['stderr']}"
    assert result["corr_id"] == expected_id, (
        f"Expected CORR_ID={expected_id}, got {result['corr_id']}"
    )
    assert result["pull_signal"] == "1", (
        f"Expected PULL_SIGNAL=1 for 'pull' line 2, got {result['pull_signal']}"
    )


def test_one_line_legacy_pull_trigger_sets_unknown(tmp_path):
    """Legacy 1-line 'pull' trigger: CORR_ID=unknown, PULL_SIGNAL=1."""
    result = _run_corr_block("pull", tmp_path)
    assert result["exit_code"] == 0, f"Script failed: {result['stderr']}"
    assert result["corr_id"] == "unknown", (
        f"Expected CORR_ID=unknown for legacy 1-line trigger, got {result['corr_id']}"
    )
    assert result["pull_signal"] == "1", (
        f"Expected PULL_SIGNAL=1 for legacy 'pull' trigger, got {result['pull_signal']}"
    )


def test_one_line_legacy_empty_trigger_sets_unknown(tmp_path):
    """Legacy 1-line empty trigger: CORR_ID=unknown, PULL_SIGNAL=0."""
    result = _run_corr_block("", tmp_path)
    assert result["exit_code"] == 0, f"Script failed: {result['stderr']}"
    assert result["corr_id"] == "unknown", (
        f"Expected CORR_ID=unknown for legacy empty trigger, got {result['corr_id']}"
    )
    assert result["pull_signal"] == "0", (
        f"Expected PULL_SIGNAL=0 for empty trigger, got {result['pull_signal']}"
    )


def test_no_trigger_file_sets_manual_prefix(tmp_path):
    """No trigger file: CORR_ID starts with 'manual-', PULL_SIGNAL=0."""
    result = _run_corr_block(None, tmp_path)  # None = don't create file
    assert result["exit_code"] == 0, f"Script failed: {result['stderr']}"
    assert result["corr_id"].startswith("manual-"), (
        f"Expected CORR_ID to start with 'manual-', got {result['corr_id']}"
    )
    assert result["pull_signal"] == "0", (
        f"Expected PULL_SIGNAL=0 for manual trigger, got {result['pull_signal']}"
    )


def test_two_line_non_pull_signal_sets_pull_signal_0(tmp_path):
    """2-line trigger where line 2 is not 'pull': PULL_SIGNAL=0."""
    expected_id = "a3f9e1b2-1234-5678-abcd-000000000002"
    result = _run_corr_block(f"{expected_id}\n", tmp_path)
    assert result["exit_code"] == 0, f"Script failed: {result['stderr']}"
    assert result["corr_id"] == expected_id
    assert result["pull_signal"] == "0", (
        f"Expected PULL_SIGNAL=0 when line 2 is empty, got {result['pull_signal']}"
    )
