#!/usr/bin/env bash
# Bay CLI wrapper — do not edit; regenerated by .bay/bootstrap.sh and 'bin/bay setup'.
#
# This file is the single source of truth for the consumer's bin/bay wrapper.
# Both writers (bootstrap.sh and bay_cli.commands.framework._ensure_bin_wrapper)
# copy it verbatim, so the two paths can never drift.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ ! -d "${SCRIPT_DIR}/.bay" ]; then
    echo "Error: .bay/ directory not found." >&2
    echo "Clone the framework and bootstrap it:" >&2
    echo "  git clone https://github.com/AltanS/bay.git .bay" >&2
    echo "  .bay/bootstrap.sh" >&2
    exit 1
fi

unset VIRTUAL_ENV 2>/dev/null
exec uv run --project "${SCRIPT_DIR}/.bay" bay "$@"
