#!/usr/bin/env python3
"""Generate contents lists for README.md and long docs/*.md files.

Run with `python3 -I scripts/docs-toc.py` (stdlib only).
Default mode rewrites files in place. `--check` changes nothing and exits 1
and lists each file whose list is missing or stale.

A file gets a list when it has more than MIN_LINES lines once the list block
is removed. The list holds `##` and `###` headings. Anchors follow GitHub's
slug rules.
"""
from __future__ import annotations

import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIN_LINES = 150
START = "<!-- toc: generated by scripts/docs-toc.py, do not edit -->"
END = "<!-- /toc -->"

FENCE_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})")
HEADING_RE = re.compile(r"^ {0,3}(#{1,6})[ \t]+(.*?)(?:[ \t]+#+)?[ \t]*$")
LINK_RE = re.compile(r"!?\[([^\]]*)\]\([^)]*\)")


def slug_base(text: str) -> str:
    """GitHub slug before duplicate handling."""
    text = LINK_RE.sub(r"\1", text).lower()
    out = []
    for ch in text:
        if ch in " -_":
            out.append("-" if ch == " " else ch)
        elif unicodedata.category(ch)[0] in "LNM":
            out.append(ch)
    return "".join(out)


def headings_at(lines: list[str]) -> list[tuple[int, int, str]]:
    """All ATX headings outside fenced code, as (line index, level, text)."""
    found = []
    fence = None
    for idx, line in enumerate(lines):
        m = FENCE_RE.match(line)
        if m:
            marker = m.group(1)
            if fence is None:
                fence = marker[0], len(marker)
            elif marker[0] == fence[0] and len(marker) >= fence[1] and not line.strip()[len(marker):].strip():
                fence = None
            continue
        if fence:
            continue
        h = HEADING_RE.match(line)
        if h:
            found.append((idx, len(h.group(1)), h.group(2).strip()))
    return found


def headings(lines: list[str]) -> list[tuple[int, str]]:
    """All ATX headings outside fenced code, as (level, text)."""
    return [(lvl, text) for _, lvl, text in headings_at(lines)]


def anchors(heads: list[tuple[int, str]]) -> list[str]:
    """Unique anchors for every heading, in order, as GitHub assigns them."""
    seen: set[str] = set()
    counts: dict[str, int] = {}
    result = []
    for _, text in heads:
        base = slug_base(text)
        slug = base
        n = counts.get(base, 0)
        while slug in seen:
            n += 1
            slug = f"{base}-{n}"
        counts[base] = n
        seen.add(slug)
        result.append(slug)
    return result


def link_text(text: str) -> str:
    """Escape square brackets outside inline code spans."""
    parts = re.split(r"(`+[^`]*`+)", text)
    return "".join(p if p.startswith("`") else p.replace("[", "\\[").replace("]", "\\]") for p in parts)


def build_block(lines: list[str]) -> list[str]:
    heads = headings(lines)
    slugs = anchors(heads)
    entries = []
    for (level, text), slug in zip(heads, slugs):
        if level in (2, 3):
            entries.append(f"{'  ' if level == 3 else ''}- [{link_text(text)}](#{slug})")
    return [START, "**Contents**", "", *entries, END]


def strip_block(lines: list[str]) -> list[str]:
    """Remove an existing block and the blank line that was added before it."""
    if START not in lines:
        return lines
    i = lines.index(START)
    j = lines.index(END, i)
    start = i - 1 if i > 0 and lines[i - 1] == "" else i
    rest = lines[j + 1:]
    if start == 0 and rest[:1] == [""]:
        rest = rest[1:]
    return lines[:start] + rest


def insert_block(lines: list[str], block: list[str]) -> list[str]:
    h1 = next((i for i, lvl, _ in headings_at(lines) if lvl == 1), None)
    if h1 is None:
        # No H1: start after a leading fenced banner if there is one, so a
        # README keeps its banner and badges on top. Else the block goes first.
        h1 = -1
        if lines and FENCE_RE.match(lines[0]):
            close = next((i for i in range(1, len(lines)) if FENCE_RE.match(lines[i])), None)
            if close is None:
                return block + [""] + lines
            h1 = close
        else:
            return block + [""] + lines
    first = next((i for i in range(h1 + 1, len(lines)) if lines[i].strip()), None)
    if first is None:
        return lines + [""] + block
    b = next((i for i in range(first + 1, len(lines)) if not lines[i].strip()), None)
    if b is None:
        return lines + [""] + block
    return lines[:b] + [""] + block + lines[b:]


def render(text: str) -> str | None:
    """New file text, or None when the file is too short for a list."""
    lines = strip_block(text.split("\n"))
    if len(lines) - (lines[-1:] == [""]) <= MIN_LINES:
        return None
    return "\n".join(insert_block(lines, build_block(lines)))


def targets() -> list[Path]:
    return [ROOT / "README.md", *sorted((ROOT / "docs").glob("*.md"))]


def main(argv: list[str]) -> int:
    check = "--check" in argv
    bad = []
    for path in targets():
        old = path.read_text(encoding="utf-8")
        new = render(old)
        if new is None or new == old:
            continue
        bad.append(path.relative_to(ROOT))
        if not check:
            path.write_text(new, encoding="utf-8")
    for p in bad:
        print(f"{'stale or missing' if check else 'updated'}: {p}")
    return 1 if (check and bad) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
